#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 28 11:31:22 2023

@author: Hermann Sockeng,  email: hermannsockeng@gmail.com
"""
#import sys
#from nltk.tokenize import word_tokenize

import preprocessing as P
import Anaphora_filter as AF
import PartOfSpeech as POS





def anaphora_classifier_system(text):
    
    language = 'german'
    p = P.TextTokenizer(language)
    
    sent_tok = p.tokenize_sentences(text)
#    word_tok = p.word_tokenizer()
    
#    pos = POS.find_pa(tokenized_sent=sent_tok)
    
#    af = AF.anaphora_filter(sent_tok, word_tok)
    
    for sentence in sent_tok:
        word_tok = p.tokenize_words(sentence)
        pa_set = POS.find_pa(word_tok)
        if len(pa_set) == 0:
            pass
        else:
            for pa in pa_set:
                af = AF.anaphora_filter(sentence, word_tok)
                
                if pa[:2] ==  'da' or pa[:2] == 'Da' or pa[:4] == 'hier' or pa[:4] == 'Hier':  
                    af.Da_or_Hier_PA_classifier(pa, sentence, sent_tok[sent_tok.index(sentence)-1], sent_tok[-1])
                    
                elif pa[:2] == 'wo' or pa[:2] == 'Wo':
                    af.Wo_PA_classifier(pa, sentence)
                else:
                    print(f"Something wrong with the pronominal adverb '{pa}'. It's neither wo- nor 'da or hier'!")
             
                    
             
                
 
              
text1 = '''Damit frische Blüten und Blätter sich entfalten können, müssen vergilbte Pflanzenteile entfernt werden.
"Dazu darf keine Schere verwendet werden", warnt Legrand.
"Auch wenn es schwer fällt: Reißen Sie alte Blüten und gelbe Blätter direkt an der Knolle mit einer drehenden Bewegung und einem kräftigen Ruck nach unten raus." 
Dadurch wird vermieden, dass sich Fäulnis bildet.
Die niederländischen Wissenschaftler, die dem Phänomen einen Namen gegeben haben, stellten fest, dass "Leisure sickness" vor allem Menschen mit hohem Arbeitspensum und Verantwortungsgefühl betrifft.
Psychologen machen auch Bewegungsmangel und einen hohen Medienkonsum für die "Freizeit-Krankheit" verantwortlich.
"Menschen müssen wieder mehr Sorge dafür tragen, dass der Körper Entspannung findet", meint Psychotherapeut Soljan.
Allerdings sollte man analysieren, was wirklich gut tut. "Nicht bloß fernsehen", rät der Experte. Stattdessen solle man lieber in Ruhe ein Bad nehmen, einen Tee trinken oder mal wieder nett den Frühstückstisch decken.
Soljan hält die Entwicklung des Phänomens "Leisure sickness" für gravierend: "Wenn man den Prozess nicht unterbricht, kann es im schlechtesten Fall zu psychosomatischen Erkrankungen kommen."'''        
    
print("\n \n")    
    
#anaphora_classifier_system(text1)    
    
    
text2 = '''Wozu die DSV-Läufer dennoch imstande sind, zeigte der Frankenhainer Jens Filbrich.
Auf dem klassischen Teilstück diktierte er das Rennen mit. 
"Ich habe mich richtig gut gefühlt. Doch dann kam ein Sturz dazwischen, und schon waren 20, 25 Plätze verloren.
Zudem habe ich mir das Schienbein richtig wehgetan und konnte im Skating nicht so, wie ich wollte", sagte der Thüringer.
Zum Glück hat Henry eine schlaue Schulfreundin. "Sie schreibt für mich in der Schule mit und erklärt es mir später."
Trotzdem haben sich seine Noten im vergangenen Jahr verschlechtert.
Henry weiß warum: "Wegen der Weltmeisterschaft war so viel dazwischen, dass ich ab und zu eine Vier kassieren musste.
Bisher hatte ich meistens Einsen und Zweien." Momentan geht Henry in die achte Klasse.
Den Schulabschluss will er auf jeden Fall schaffen — und danach will er Motocross-Berufsfahrer werden. '''    
    
    
#anaphora_classifier_system(text2, language)    
    
#print("\n \n")     
    
text3 = '''Damit sich alle Fans dieses Sportes auf die kommende Saison an den Stränden vorbereiten können, findet am 24. Mai 2008 von 9.00 Uhr bis 18.00 Uhr der 1.
Grabower-Beachday statt. Hierhinter verbirgt sich ein Beachvolleyball-Turnier, auf insgesamt 4 Feldern, mit spannen-den Spielen den ganzen Tag.
Anmelden können sich begeisterte Amateur Beachvolleyballteams als Mixed oder "Normal"-Team bis zum 13.05. 2008 unter folgenden Telefonnummern:GWaldbad, 03 87 56 / 27 7 12 oder.

Die Hammelburger Wehr führte den Lehrgang auch durch, weil das neue Löschfahrzeug LF 20/20 mit einem Notfallrucksack ausgerüstet ist.
Hierin findet sich ein Großteil der medizinischen Geräte, mit denen auch ein Rettungswagen ausgestattet ist.
"Wenn wir solche Geräte haben, brauchen wir natürlich auch Leute, die damit umgehen können", betonte Rettungsassistent Maximilian Zoll, der den Kurs gemeinsam mit Frank Karrlein leitete.'''    
    

#anaphora_classifier_system(text3, language)    

#print("\n \n")     
"""    
all_Das_PAK = '''Bei den Weltcup-Rennen in Adelboden (Herren) und Altenmarkt-Zauchensee (Damen) nimmt der Deutsche Skiverband wieder Podestplätze in Angriff. Daran änderte auch Rang 16 von Neureuther am Donnerstagabend im Flutlicht beim Sieg des Schweden Andre Myhrer nichts. "Vom Selbstvertrauen war das Rennen trotzdem gut. Ich weiß, ich bin gut drauf und lass' mich nicht rausbringen", betonte der zweimalige Weltcup-Sieger Neureuther, der im WMWinter noch ohne "Stockerl" ist. "Ich habe mich heute nicht so gut bewegt, das werde ich am Sonntag mit Sicherheit besser machen." Positiv gestimmt reiste er nach Adelboden — neben Garmisch der einzige Ort, auf dem er schon zweimal auf dem Podest stand.  
(SAZ11/JAN.00650 Saale-Zeitung, 08.01.2011, S. 22, Sachgebiet: Sport, Originalressort: Sport gesamt; Neureuther hakt Platz 16)
"Schade,Weihnachten ist schon vorbei." Das denken bei uns gerade einige Leute. Für andere Menschen steht das Weihnachtsfest allerdings kurz bevor. Etwa für die Kopten, die in Ägypten leben. Sie feiern Weihnachten erst Ende dieser Woche, am 7. Januar. Das liegt daran, dass sich die Kopten und einige andere christliche Gemeinschaften nach einem älteren Kalender richten. Danach ist das Weihnachtsfest am 7. Januar. Andere Tage dagegen sind sehr ähnlich. Sonntags zum Beispiel gehen viele Kopten zum Gottesdienst in eine Kirche. Einige Kinder besuchen an dem Tag auch spezielle Schulen, die Sonntagsschulen. Dort lernen sie etwas über ihre Religion. dpa  (SAZ11/JAN.00262 Saale Zeitung, 04.01.2011, S. 30, Originalressort: Kinderseite; ohne Titel)
Über ihr freiwilliges soziales Jahr, das sie in einer Kindereinrichtung auf den Philippinen verbracht hat, berichtet Maria Hüfner heute, Montag, 3. Januar, in Riedenberg. Dabei wird sie von ihrer Arbeit und von dem fernen Land, dessen Sitten und Gebräuchen sowie von den
Begegnungen mit den Menschen erzählen. Beginn ist um 19 Uhr im Kuratiesaal. red (SAZ11/JAN.00003 Saale-Zeitung, 03.01.2011, S. 14; Bilder und Berichte von Philippinen)
Mechanisch Ob kleiner Wecker oder große Kirchturmuhr — mechanische Uhren funktionieren im Prinzip gleich: in der Uhr arbeitet ein Räderwerk, ein Set aus verschiedenen Zahnrädern. Die werden in Bewegung gesetzt. Gewicht Bei großen Uhren übernimmt in der Regel ein Gewicht diese Aufgabe. Bei einer Armbanduhr geschieht das meist, indem man außen an der Uhr ein Rädchen dreht. Man zieht die Uhr auf. Dadurch wird im Gehäuse eine Feder gespannt, die neue Energie liefert. (SAZ11/JAN.00119 Saale-Zeitung, 03.01.2011, S. 26; Uhrenkunde)

Die Atomuhr ist die genaueste Uhr, die bisher erfunden wurden. Atome sind die kleinsten Bausteine der Natur. Alles besteht aus Atomen — wir auch. Atomuhren bringen bestimmte Atome dazu, dass sie extrem oft ihren Energiezustand ändern. Dadurch schwingen die Atome pro Sekunde knapp zehn Milliarden mal regelmäßig hin und her. Diese Schwingungen werden gezählt. Daher kann die Atomuhr genau angeben, wann eine Sekunde vorbei ist. Zum Vergleich: Eine Pendeluhr schwingt einmal pro Sekunde hin und her. Wenn eine Schwingung unregelmäßig ist, wirkt sich das viel stärker aus. dpa (SAZ11/JAN.00119 Saale-Zeitung, 03.01.2011,S.26;Uhrenkunde)

Damit frische Blüten und Blätter sich entfalten können, müssen vergilbte Pflanzenteile entfernt werden. "Dazu darf keine Schere verwendet werden", warnt Legrand. "Auch wenn es schwer fällt: Reißen Sie alte Blüten und gelbe Blätter direkt an der Knolle mit einer drehenden Bewegung und einem kräftigen Ruck nach unten raus." Dadurch wird vermieden, dass sich Fäulnis bildet. (SAZ11/JAN.00258 SaaleZeitung, 04.01.2011, S. 17; Kühler Platz für bunte Blumen)
Die niederländischen Wissenschaftler, die dem Phänomen einen Namen gegeben haben, stellten fest, dass "Leisure sickness" vor allem Menschen mit hohem Arbeitspensum und Verantwortungsgefühl betrifft. Psychologen machen auch Bewegungsmangel und einen hohen Medienkonsum für die "Freizeit-Krankheit" verantwortlich. "Menschen müssen wieder mehr Sorge dafür tragen, dass der Körper Entspannung findet", meint Psychotherapeut Soljan. Allerdings sollte man analysieren, was wirklich gut tut. "Nicht bloß fernsehen", rät der Experte. Stattdessen solle man lieber in Ruhe ein Bad nehmen, einen Tee trinken oder mal wieder nett den Frühstückstisch decken. Soljan hält die Entwicklung des Phänomens "Leisure sickness" für gravierend: "Wenn man den Prozess nicht unterbricht, kann es im schlechtesten Fall zu psychosomatischen Erkrankungen kommen." (SAZ11/JAN.00276 Saale-Zeitung, 04.01.2011, S. 34; Mit der Ruhe kommt die)
Martin Schmitt stürzte von Wolke sieben ins Jammertal, "Überflieger" Simon Ammann träumte nach seinem Höhenflug beim chaotischen Neujahrsspringen dagegen schon vom ersten Vierschanzentournee-Triumph. Dafür rangen Österreichs vom Winde verwehte Ski-Adler nach der schweren Schlappe in Garmisch-Partenkirchen mühsam um ihre Fassung, die Schmitt trotz seines Ausscheidens in der Qualifikation für das dritte Springen in Innsbruck nicht verlor. (SAZ11/JAN.00011 Saale-Zeitung, 03.01.2011, S. 16; Schmitt nach Hoch im Jammertal)
Die Bundesbürger müssen 2011 laut DIHK-Schätzung für Reisen wieder tiefer in die Tasche greifen. Gründe für den Preisanstieg seien vor allem die neue Flugverkehrsabgabe und die in vielen Städten beschlossene "Bettensteuer". Besonders Flüge und Pauschalreisen dürften sich verteuern. Dagegen blieben die Preise in der Gastronomie weitgehend stabil, sagte der Präsident des Deutschen Industrie- und Handelskammertages (DIHK) , Hans Heinrich Driftmann. Insgesamt seien jedoch die Geschäftserwartungen der Branche deutlich besser als
noch vor einem Jahr. Nach dem jüngsten DIHK-Tourismusreport wollen rund 40 Prozent der Reisebüros und 29 Prozent der Reiseveranstalter die Kostensteigerungen an ihre Kunden weitergeben. dpa (SAZ11/JAN.00017 Saale-Zeitung, 03.01.2011, S. 18; DIHK:Reisen werden teurer)
Der Dirigent, der gegen den Zusatz "Star" nichts einzuwenden hat, behauptet dagegen, man habe einvernehmlich Zärtlichkeiten ausgetauscht und dabei sei die junge schüchterne Geigerin ganz schön aus sich "raus gegangen". Wang, von 2006 bis 2008 Generalmusikdirektor der Stadt Würzburg, hat gestern die vermutlich letzte Chance "verspielt", ohne Urteil aus den Schlagzeilen herauszukommen. (SAZ11/JAN.00221 Saale-Zeitung, 04.01.2011, S. 8; Entschuldigung abgelehnt)
Allein, dass die Verunreinigung von belasteten Würstchen oder Burgern herrührt, hält Krahl für "eher unwahrscheinlich". Dies setze voraus, "dass dort tonnenweise dioxinverseuchtes Fleisch gebraten worden ist". Ungleich plausibler sei dagegen, dass das verarbeitete Speiseöl
bereits tierische Fette enthalten habe: "Und die dafür verarbeiteten Tiere könnten wiederum mit dioxinverseuchtem Futter gefüttert worden sein." Was Krahl hier nur vage andeutet, wäre nichts anderes als ein aberwitziger Kreislauf der Kontaminierung. Mit dioxinverseuchtem
Futter genährte Tiere kontaminieren Speiseöl und geben ihr Gift später, dann in einem weiteren Produktionsschritt zu Futtermittel verarbeitet, an andere Tiere weiter. (SAZ11/JAN.00372 Saale-Zeitung, 05.01.2011, S. 24; ohne Titel)
Drei Fahrzeuge waren an einem Unfall auf der Staatsstraße 2290 zwischen den Abzweigungen Gefäll und Premich beteiligt. Der 53-jährige Fahrer des vordersten Fahrzeugs verminderte seine Geschwindigkeit stark, als er durch die tiefstehende Sonne geblendet wurde. Der dahinter fahrende 51-Jährige bremste ebenfalls ab. Eine 25-jährige Frau bemerkte das zu spät und fuhr trotz Vollbremsung auf den mittleren Wagen auf, der dann noch leicht auf den ersten Pkw geschoben wurde. Fünf von acht Fahrzeuginsassen wurden leicht verletzt in Krankenhäuser gebracht. Die drei Fahrzeugführer blieben unverletzt. Es entstand ein Gesamtschaden von 26 500 Euro. Die Unfallverursacherin erwartet ein Verfahren wegen fahrlässiger Körperverletzung. pol (SAZ11/JAN.00213 Saale-Zeitung, 04.01.2011, S. 6; Drei Autos)
Auch für mobile Geräte gibt es Lernspiele. Cornelsen bietet etwa für iPhone, iPod touch und iPad "Lernsnacks". Dahinter verbergen sich Matheübungen zu Themen wie Zins- oder Prozentrechnung. Die Basis-App für 79 Cent enthält 200 Aufgaben zur Prozentrechnung. Jedes weitere Häppchen wird für knapp 3 Euro in Apples Online-Laden, dem iTunes App Store, angeboten. Die Erweiterungen sollen monatlich erscheinen. Die App "MyBricks Zahlen" von Terzio richtet sich an die Jüngsten. Kinder werden dazu animiert, mit großen und bunten Bausteinen Zahlen zusammenzubauen. Das soll sie spielerisch an deren Laut und Form heranführen. (SAZ11/JAN.01205 Saale-Zeitung, 13.01.2011, S. 29; ohne Titel)
Mancher Autofahrer dürfte gestern die kurzen Wartezeiten auf den Einfallstraßen nach Bad Brückenau genossen haben, verhießen doch die Behinderungen am Morgen eine Schonung der Stoßdämpfer am Abend: "Wir bleiben dahinter, dass die gravierendsten Schäden schnell
beseitigt sind", berichtet Stefan Zehe, Leiter der Straßenmeisterei Hammelburg, dass gestern eine große Aktion auf den Bundesstraßen rund um Bad Brückenau startete. (SAZ11/FEB.00653 Saale-Zeitung, 05.02.2011, S. 19; Nicht die tiefsten, aber die größten Löcher)

Waldfenster Die Jahreshauptversammlung des Musikvereins Waldfenster findet am Freitag, 14. Januar, um 19.30 Uhr im Gasthaus "Krone" statt. Auf der Tagesordnung stehen neben den Berichten des Vorsitzenden und der Abteilungen und den Regularien Neuwahlen und eine Satzungsänderung. Anträge zur Generalversammlung müssen schriftlich bis spätestens 8. Januar beim 1. Vorsitzenden eingereicht werden, damit sie in der Versammlung behandelt werden können. red (SAZ11/JAN.00025 Saale-Zeitung, 03.01.2011, S. 6; Neuwahlen und eine Änderung)

Nicht nur das Jahr 2010 wurde von der "Egerländer Blasmusik" bei einem Konzert im Bad Bockleter Kursaal musikalisch verabschiedet, sondern auch der langjährige Dirigent Rudi Bock. Damit ging nach 16 Jahren eine Ära zu Ende, die die Kapelle
und auch deren Musikstil entscheidend mit geprägt hat. (SAZ11/JAN.00073 Saale-Zeitung, 03.01.2011, S. 5; Eine Ära ging zu Ende)
Die Feuerwehr Untererthal führt am Donnerstag, 6. Januar, ihre Jahreshauptversammlung durch. Beginn ist um 19 Uhr im Schulungsraum des Feuerwehrgerätehauses. Auf der Tagesordnung stehen unter anderem ein Bericht des Kommandanten und ein
Jahresrückblick. Im Anschluss werden vereinsinterne Ehrungen und Neuaufnahmen von Mitgliedern vorgenommen. Danach wählen die Floriansjünger ihren Kommandanten sowie einen 1. und 2. Vorsitzenden. mr (SAZ11/JAN.00052 Saale-Zeitung, 03.01.2011, S. 9; Wahlen bei der Wehr)
sich am Dreikönigstag Obererthal Der FCN-Fanclub trifft sich am Dreikönigstag, Donnerstag, 6. Januar, im Gasthaus Brust in Obererthal. Um 15 Uhr ist zunächst Kegeln angesagt, danach wird Bingo gespielt und es gibt ein gemütliches Beisammensein. (SAZ11/JAN.00082
Saale-Zeitung, 03.01.2011, S. 7; ohne Titel)
Das Feuerwehrhaus wurde in dieser Zeit umgebaut und ein Schulungsraum eingerichtet, der Atemgeräteschutz eingeführt und die Vereinsfahne angeschafft. Daneben wurde unter seiner Federführung der Fuhrpark aufgerüstet. (SAZ11/JAN.00604 Saale-Zeitung, 08.01.2011, S. 8; Aufgabe in jüngere Hände gelegt)
Am 1. Januar kurz nach 13 Uhr bemerkte der Eigentümer einer Scheune in Rothhausen starke Rauchentwicklung, die aus der Scheune kam. Kurz darauf stand das Gebäude schon in Flammen. Die Feuerwehren aus Rothhausen, Thundorf, Münnerstadt, Theinfeld, Maßbach,
Stadtlauringen, Weichtungen sowie die Drehleiter aus Bad Kissingen waren mit einem Großaufgebot zur Brandbekämpfung angerückt. Die Maßbacher Feuerwehr kam allerdings erst auf Umwegen zum Brandort, da man sie nach Thundorf geschickt hatte, so Einsatzleiter Holger Ulrich. (SAZ11/JAN.00034 Saale-Zeitung, 03.01.2011, S. 12; Die Flammen schlugen hoch)
Angeblich mault der Franke gern, er macht gerne nieder. Am liebsten sich selbst und das, was er hat. Der Kissinger mault über die Kur. "Die Kur ist tot", lautet ein oft gehörter Satz, wobei offenbleibt, was da mit Kur gemeint ist. Die private Vorsorge, die Stationäre Rehabilitation oder die Anschlussheilbehandlung? Schaut man auf die Statistik, hat die Übernachtungszahl bei den Versicherungsgästen sogar leicht zugenommen. Es kommt darauf an, was der Standort Bad Kissingen aus seiner Kompetenz macht. Zum Beispiel die
Klinik am Kurpark mit ihrer Kira-Studie. Die "Kur" ist nicht tot. (SAZ11/JAN.00062 Saale-Zeitung, 03.01.2011, S. 1; Die Kur ist)

Die Denkpause für Westerwelle ist nun beendet. Wird er in Stuttgart nun seinen Rückzug vom Parteivorsitz ankündigen? Wird er einen Neuanfang der FDP mit einer jüngeren Mannschaft um Generalsekretär Christian Lindner in Aussicht stellen? Nichts deutet darauf hin, dass sich der vor wenigen Tagen 49 gewordene Westerwelle kampflos vom politischen Acker machen wird. Im Gegenteil: Die meisten FDP-Auguren sind sich darin einig, dass Westerwelles einzige Chance die politische Offensive ist. Befragungen der Parteibasis bestätigen dieses Bild: 77 Prozent der FDP-Anhänger wollen den Super-Wahlkämpfer aus Bonn, der seiner Partei bis 2009 Wahlsiege in Serie verschaffte, auch weiter als Chef behalten. (SAZ11/JAN.00096 Saale-Zeitung, 03.01.2011, S. 22; Westerwelle kämpft um sein Partei-Amt)
Mit viel Herzblut und Engagement hatte Fridolin Fritz ein Jahrzehnt lang den Ortsverband Schondra als Vorsitzender geleitet. Dafür war er kürzlich zum Ehrenvorsitzenden ernannt worden (die Heimatzeitung berichtete). Darauf ist er sichtlich stolz, die Urkunde hängt in seinem Arbeitszimmer an der Wand. Aus gesundheitlichen Gründen und auch vom Alter her, wie er sagt, wollte er das Zepter aus der Hand geben und er freut sich, dass er jüngere Nachfolger gefunden hat. (SAZ11/JAN.00248 Saale-Zeitung, 04.01.2011, S. 15; Als der Kassierer noch durchs Dorf lief...)
Das Auto wurde dann mit dem Rettungssatz vorschriftsmäßig zerlegt. Im Rahmen eines
Fachhochschul-Projektes wurde die Übung aufgezeichnet. Daraus soll ein Werbefilm für Feuerwehren entstehen. (SAZ11/JAN.00979 Saale-Zeitung, 12.01.2011, S. 6; Weiter unter bewährter Führung)
Hoffnungen setzt der SVN-Vorstand nicht nur in die Zukunft der aktiven Mannschaft in der aktuell laufenden Oberliga-Runde, sondern auch darein, dass das Projekt Umbau Westpfalzstadion (aus dem Hartplatz soll ein Kunstrasenplatz werden) noch in diesem Jahr realisiert werden kann. mw (SBZ10/AUG.09167 Saarbrücker Zeitung, 23.08.2010; "Einmal SVN, immer SVN")
Jedes Team berät sich ein letztes Mal - "Auf die Plätze, fertig, los!" - und jedes Team beginnt seine Arbeit: Lisdorf klebt den Nagel an die Dachlatte, spannt das Seil über das Feld hin und zurück, wie bei einer Seilbahn. Sie befüllen die Flaschen mit Wasser, blasen die Luftballons
auf und füllen das Wasser darein. Die Luftballons werden an das Seil gehängt und über die Gießkanne gezogen. Nun wird mit dem Nagel der Ballon zerstochen und das Wasser spritzt in die Gießkanne. Die anderen Stadtteile haben ihre eigene Technik: Picard baut eine Art Rohr aus der Dachlatte und dem Klebeband. Die effektivste Technik, die die Lisdorfer die Punkte ihres eigenen Spieles kostet, denn Picard hatte auch eine gute Kräuterfee. (SBZ11/AUG.09368 Saarbrücker Zeitung, 23.08.2011; Die Kräuterfee brachte den Pokal im StadtteileWettkampf)
Sie können mal ausprobieren, Kartoffeln in Tonnen anzubauen. Dazu nehme man eine alte Mülltonne oder ein ähnliches Gefäß mit bis zu einem Sechstel gefüllt mit Erde. Dann pflanze man darein eine oder mehrere Kartoffeln. Beim Wachsen des Krautes füllt man immer wieder
vor der Blüte Erde nach, bis die Tonne voll ist. Zur Erntezeit einfach nur Ausleeren und sich über die reiche Kartoffelzahl freuen. Für einen Jahresvorrat wird es zwar nicht reichen, aber Idealisten genießen die eigenen Knollen dann trotzdem sehr. (SKU01/APR.15749 Südkurier, 25.04.2001; Kartoffeln in der Mülltonne)
Das Problem lag darin, dass sich die Organisten beim Spiel an den rund 25 Meter auseinander stehenden Instrumenten nicht sehen konnten und dennoch präzise spielen mussten. Das gelang ausgezeichnet, und die Zuhörer konnten auf einer Leinwand beiden auf Finger und Füße schauen. (SAZ11/JAN.00070 Saale-Zeitung, 03.01.2011, S. 4; Musik für)
Auf Leverkusen und den FSV Mainz 05 haben die Dortmunder nach der
Hinrunde zehn Punkte Vorsprung. "Wir müssen aufpassen, dass der Mannschaft nicht zu hohe Erwartungen aufgebürdet werden. Denn darin sehe ich die größte Gefahr für die Rückrunde", sagte BVB- Geschäftsführer Hans-Joachim Watzke den "Ruhr Nachrichten" .
(SAZ11/JAN.00156 Saale-Zeitung, 04.01.2011, S. 21; Zum Training ins warme Spanien)
CSU-Chef Horst Seehofer sagte: "Beim Bildungspaket können wir darüber reden, ob der Kreis der Empfänger ausgeweitet wird und wie man das möglichst unbürokratisch gestaltet. Sinnvoll sind treffsichere Lösungen bei Mindestlöhnen in bestimmten Branchen, vor allem bei der Zeitarbeit." (SAZ11/JAN.00029 Saale-Zeitung, 03.01.2011, S. 19; DGB rät zum Widerspruch gegen Hartz-IV-Bescheide)
Edgar Bartl Bad Kissingen Geht es nach dem bayerischen Ministerrat und der Unterfränkischen Regierung, werden die Kommunen künftig viel enger zusammenarbeiten. Auch und gerade bei den Standesämtern. Darüber informierten bei einer Dienstbesprechung Peter Müller (Regierung) und Robert Bromma (Amt für Landwirtschaft) die Bürgermeister aus dem Landkreis. (SAZ11/JAN.00192 Saale-Zeitung, 04.01.2011, S. 4; Kein "Kahlschlag" bei den Standesämtern)
Aufbruch der Jugend Das zweite große Thema betraf die Jugend. Der Aufbruch nach dem Zweiten Weltkrieg war plötzlich in eine Krise geraten. "Und auch wir als Jugendseelsorger von der ersten Garde her waren nicht mehr fähig, dies aufzufangen. Darum musste man fragen: Wie gehen wir mit der heutigen Jugend um, nachdem die Jugend plötzlich ganz andere Ziele hatte, andere Aufgaben sah, beispielsweise die Öko-Frage oder den Frieden." (SAZ11/JAN.00547 Saale-Zeitung, 06.01.2011, S. 33; Die Synode hat den Anstoß zur Ökumene gegeben)
Nach 1945 konnten viele Forscher der Gesellschaft ihre Karrieren fortsetzen. "Da wurde unterschieden, ob jemand ein guter oder ein schlechter Forscher war", sagt Rürup. "Es ging nicht darum, ob jemand Nazi gewesen war oder nicht." Die Kaiser-Wilhelm-Gesellschaft
änderte ihren Namen. Nobelpreisträger Max Planck, der wie Otto Hahn als integer und unbelastet galt, übernahm im hohen Alter noch einmal die Präsidentschaft. Die Gesellschaft erhielt seinen Namen. (SAZ11/JAN.00869 Saale-Zeitung, 11.01.2011, S. 34; ohne Titel)
17 593 Entleihungen konnten die ehrenamtlichen Mitarbeiterinnen der katholischen öffentlichen Bücherei in Garitz im Jahr 2010 registrieren. Das teilte Büchereileiterin Silvia Ammersbach mit. Demnach sind in der Bücherei insgesamt 6985 Medien (Bücher, Spiele, CDs, Tonkassetten, CD Roms, Filme, Zeitschriften) vorhanden. 449 Medien kamen im vergangenen Jahr neu hinzu, 583 mussten wegen Überalterung oder Verschleiß aussortiert werden. 494 Leser nutzten das kostenlose Angebot der Einrichtung. Darunter finden sich nicht nur Garitzer Bürger, so Silvia Ammersbach, sondern auch eifrige Leser aus anderen Stadtteilen und den umliegenden Orten. Viele Leserwünsche konnten durch die Nutzung der Katholischen Büchereiarbeit (KBA) erfüllt werden. Zur Ergänzung des eigenen Bestandes werden jedes Jahr rund 1000 Bücher von der KBA ausgeliehen. Diese "Austauschbücher" bleiben sechs Monate in Garitz. (SAZ11/JAN.00288 Saale-Zeitung, 05.01.2011, S. 2; 494 nutzten 6985 Medien 17 593 Mal)

Im April 1953 heiratete er die belgische Prinzessin Joséphine- Charlotte, die Schwester der belgischen Könige Baudouin I. und Albert II. Aus der Ehe gingen fünf Kinder hervor, darunter der derzeit amtierende, 54 Jahre alte Großherzog Henri. 1964 bestieg Jean den Thron, nachdem seine Mutter Charlotte abgedankt hatte. (SAZ11/JAN.00407 Saale-Zeitung, 05.01.2011, S. 31; Luxemburgs Garant für Freiheit und Unabhängigkeit)
"Die Rahmenbedingungen sind im kommenden Jahr grundsätzlich so, dass Banken gute Gewinne machen können", sagt Bankenprofessor Hans-Peter Burghof. Die Banken profitieren davon, dass Notenbanken weiter billiges Geld zur Verfügung stellen. Die Europäische
Zentralbank (EZB) dürfte beim Leitzins im Euro-Raum frühestens Ende 2011 das Rekordtief von 1,0 Prozent verlassen. Selbstbewusst plant die Deutsche Bank einen Vorsteuergewinn von 10 Milliarden Euro. Damit würde operativ der Rekord des Jahres 2007 (8,7 Mrd Euro)
eingestellt, obwohl der Branchenprimus noch die Postbank-Eingliederung stemmen muss. (SAZ11/JAN.00018 Saale-Zeitung, 03.01.2011, S. 18; Banken erster und zweiter Klasse)
Leutheusser-Schnarrenberger räumte ein, der FDP werde nicht zu Unrecht vorgeworfen, dass sich von ihren Wahlkampfversprechen zu wenig wiederfinde im Regierungshandeln. Als Außenminister habe Westerwelle klar Erfolge zu verzeichnen. Seine schlechten Umfragewerte hätten mit der Leistung der Partei insgesamt zu tun. Beim Bundesparteitag im Mai werde die Führung neu gewählt. "Vieles hängt davon ab, was Guido Westerwelle selbst möchte. Wir sollten ihn ganz persönlich entscheiden lassen, ob er noch einmal als Vorsitzender antritt", sagte die Ministerin. (SAZ11/JAN.00031 Saale-Zeitung, 03.01.2011, S. 19; Druck auf Westerwelle wächst)
Gesundheitsminister Rösler zeigte sich davon überzeugt, dass der Parteichef weiterkämpfen wird: "Guido Westerwelle ist der beste Wahlkämpfer, den wir haben. Er wird uns erfolgreich in die Wahlkämpfe des Superwahljahres 2011 führen", sagte der FDP-Politiker. Niebel
warf den Kritikern Westerwelles vor, sie wollten "ihr persönliches Süppchen kochen". (SAZ11/JAN.00031 Saale-Zeitung, 03.01.2011, S. 19; Druck auf Westerwelle wächst)
18 Taufen 18 Kinder wurden getauft, neun Jugendliche feierten Konfirmation. Trauungen gab es fünf, Bestattungen neun. Vier Gemeindemitglieder erklärten ihren Austritt aus der Kirche, zwei Personen traten in die Gemeinde ein. 1306 Mitglieder werden in der Gemeinde betreut, so Pfarrer Pennig. Davon wohnen 656 in der Kernstadt und 650 in den Außenorten. Knapp 15 Prozent der Gemeindemitglieder sind Jugendliche, rund 60 Prozent sind erwerbsfähige Erwachsene und 15 Prozent Rentner. (SAZ11/JAN.00043 SaaleZeitung, 03.01.2011, S. 11; Besinnlicher Jahreswechsel)
Auch im jetzt begonnenen Jahr stehen wieder zahlreiche Wanderungen auf dem Programm. Dazu gehören wie stets die beliebten Wanderungen mit Kurgästen. Die erste wird es am 5. April gegeben, Ziel ist das Schloss Saaleck. (SAZ11/JAN.00005 Saale-Zeitung,
03.01.2011, S. 14; Mit Fackeln auf den Volkersberg)

In der Realität sehe es heute so aus, dass viele junge Leute abends erst nach Essen, Sport und Duschen ausgehen. "Dann ist es oft 23 Uhr, und der Besuch einer Veranstaltung, bei der um 2 Uhr die Musik abgedreht wird, würde sich dann nicht mehr lohnen, wenn auch noch für den
Eintritt sechs oder acht Euro zu zahlen sind", machte Fenn deutlich. Die Folge: Die jungen Menschen würden dann lieber gleich in eine größere Stadt fahren, wo es keine Sperrstunde gebe. Daher könnte die Regelung dazu führen, dass die professionelle Gastronomie gegenüber
den Veranstaltern auf dem Land, darunter viele örtliche Vereine, bevorteilt werde. (SAZ11/JAN.00079 Saale-Zeitung, 03.01.2011, S. 7; "Sperrstunde bedroht Jugendkulturszene")
Dem soll die Kira-Studie vorbeugen. Nach vier und nach acht Monaten werden die Patienten für jeweils eine Woche in die Klinik am Kurpark zurückkehren. Dazwischen halten sie ständig telefonischen Kontakt mit ihrem Kissinger Physiotherapeuten. (SAZ11/JAN.00061
Saale-Zeitung, 03.01.2011, S. 1; Kira als Weg zur Genesung)
Wozu die DSV-Läufer dennoch imstande sind, zeigte der Frankenhainer Jens Filbrich. Auf dem klassischen Teilstück diktierte er das Rennen mit. "Ich habe mich richtig gut gefühlt. Doch dann kam ein Sturz dazwischen, und schon waren 20, 25 Plätze verloren. Zudem habe ich mir das Schienbein richtig wehgetan und konnte im Skating nicht so, wie ich wollte", sagte der Thüringer. (SAZ11/JAN.00148 Saale-Zeitung, 04.01.2011, S. 20; Teichmann steigt nach Rang 56 aus)
Zum Glück hat Henry eine schlaue Schulfreundin. "Sie schreibt für mich in der Schule mit und erklärt es mir später." Trotzdem haben sich seine Noten im vergangenen Jahr verschlechtert. Henry weiß warum: "Wegen der Weltmeisterschaft war so viel dazwischen, dass ich ab und zu eine Vier kassieren musste. Bisher hatte ich meistens Einsen und Zweien." Momentan geht Henry in die achte Klasse. Den Schulabschluss will er auf jeden Fall schaffen — und danach will er Motocross-Berufsfahrer werden. (SAZ11/FEB.01913 Saale-Zeitung, 15.02.2011, S. 30; ohne Titel)
Die Fundamente, die aus mit Beton ausgegossenen Stahlarmierungen bestehen, sind rund 350 Tonnen schwer und geben den Kolossen den nötigen Halt. Eine Anlage vom Typ V90 wiegt nach Vestas-Angaben 331 Tonnen. Bereits komplett unter der Erde verlegt sind die Kabel, die
den Strom von Gauaschach nach Hundsbach fließen lassen, wo sich ein Umspannwerk der Firma Wotan befindet. Hieran sind noch zwei weitere Anlagen des Hamburger Unternehmens angeschlossen. Dort wird die elektrische Energie dann ins öffentliche Netz eingespeist.
(SAZ11/JAN.00444 Saale-Zeitung, 06.01.2011, S. 9; Strom aus Wind für rund 3300 Haushalte)
Beim Kauf von Pflanzen und Saaten achtet der Hobbygärtner noch viel zu wenig auf Qualität. Vor allem bei Billigangeboten ist kritisch vorzugehen. Ein wenig Fachwissen und Ruhe beim Einkauf gehört schon dazu, die Spreu vom Weizen zu trennen. So hat der Bund
Deutscher Baumschulen ein Markensiegel herausgegeben, welches auf den Etiketten zu sehen ist. Hierauf müssen auch die botanischen Namen der Gehölze, die Sorten und Größen sowie Hinweise zur Pflanzung angegeben sein. Ähnlich kennzeichnen auch die Staudengärtner
ihre Produkte. (SAZ11/APR.01451 Saale-Zeitung, 12.04.2011, S. 33; Beim Einkaufen auf die Qualität achten)
Um rund 120 000 Euro blieb die Gewerbesteuer hinter den Erwartungen zurück. Die Verschuldung stieg im vergangenen Jahr um etwa 85 000 Euro auf 1,2 Millionen Euro an. Aus den laufenden Einnahmen und Ausgaben konnten dem Vermögenshaushalt 292000 Euro zugeführt werden. Hieraus lässt sich ablesen, dass die Kommune trotz angespannter finanzieller Lage noch Mittel für kommende Investitionen "erwirtschaften" konnte. Die Feststellung der Jahresrechnung und die Entlastung der Gemeindeverwaltung erfolgten einstimmig. bit (SAZ11/JUN.01069 Saale-Zeitung, 10.06.2011, S. 17; ohne Titel)
Stadtrat Christian Fenn begründete den Antrag mit den verhältnismäßig großen Waldflächen der Stadt Hammelburg. Hieraus erwachse der Kommune eine große Verantwortung gegenüber dem Forst. (SAZ11/JUN.01185 Saale-Zeitung, 11.06.2011, S. 9; "Großer Wald bedeutet)
Als dieser am Lkw vorüberfuhr, begann dieser aufgrund seines Gewichtes zu rutschen und schob sich seitlich auf den Pkw. Hierbei entstand leichter Sachschaden. red (SAZ11/JAN.00037 Saale-Zeitung, 03.01.2011, S. 12; Lkw rutscht auf Pkw)

Chorleiter im Amt bestätigt Die Bestätigung bei den Wahlen für drei Jahre erhielt ebenso Chorleiter Peter Hartmann. Er bedankte sich bei den Sängerinnen und Sängern für ihr Engagement und Treue zum Gesang; Vorsitzende Göbel wiederum für seine Gabe der Motivation, man werde sich jedoch um Verstärkung bei den Männerstimmen bemühen. Sie lobte den Probenbesuch, möchte sich aber um vermehrt öffentliche Auftritte kümmern, wozu sich das Jubiläum bereits als Einstieg anbiete. Hierbei ist an ein Singen für Lebende und Verstorbene mit anschließendem Fastenessen im April und Gestaltung von Gottesdiensten gedacht. Ein Ehrenabend im Juli, Singen mit Gastchören und Sommerfest, sowie ein Konzert mit dem Musikverein im November sind die Planungen im Jubiläumsjahr 2011. (SAZ11/JAN.00924 SaaleZeitung, 11.01.2011, S. 13; Bewegender Abschied aus dem Vereinsvorstand)
Auch Veranstaltungen wie "Hammelburg moves" wären kaum noch möglich, weil die Vereine um 2 Uhr die Musik abschalten müssten, während bei den Gastronomen noch gefeiert werden könne, betonte Alexander Stolz. "Zu kulturellem Leben gehört auch ein Nachtleben dazu, und das verträgt sich einfach nicht mit einer Sperrstunde", so der Stadtrat. Die Jugendkulturszene werde hierdurch bedroht und das Land verliere weiter an Attraktivität. (SAZ11/JAN.00079 Saale-Zeitung, 03.01.2011, S. 7; "Sperrstunde bedroht Jugendkulturszene")

"Versteigerungen drohen" Doch davon sei der Arbeitsmarkt meilenweit entfernt. Es gebe immer mehr Menschen, die nicht angemessen bezahlt würden, zum Beispiel Verkäuferinnen oder Friseurinnen, und trotz Arbeit nicht genug Geld zum Leben hätten. Sie zahlten hierdurch
auch nur geringe Beträge in die Rentenversicherung ein, wodurch ihnen auch im Alter Armut drohe. (SAZ11/JAN.00611 Saale-Zeitung, 08.01.2011, S. 9; Zunahme der Armut hat viele Gründe)
Aufgrund der öffentlichen Ausschreibung des Bauvorhabens kann frühestens im Oktober mit dem Start gerechnet werden. Die Regierung schlug deshalb vor, einen Teil der Bauarbeiten vorzuziehen, wie zum Beispiel die nichtöffentliche Erschließung auf dem Baugrundstück.
Hierdurch wäre dann der Baubeginn nachgewiesen. Die restlichen Ausschreibungen könnten dann auch zu einem späteren Zeitpunkt erfolgen. (SAZ11/JUN.01579 Saale-Zeitung, 15.06.2011, S. 18; Baubeginn)
Die Insekten kommen nicht wieder hoch, denn feinste, abwärts gerichtete Haare im oberen Teil des Tunnels halten sie unten. "Hierein werden von den Pflanzen Verdauungsenzyme abgegeben, die auch im menschlichen Magen vorkommen", sagt der Züchter und Buchautor
Thomas Carow. Bakterien unterstützen den Zersetzungsvorgang. (SAZ11/MAI.02058 Saale-Zeitung, 17.05.2011, S. 33; Vorsicht, gefräßige Fallen!)
Damit sich das nicht wiederholt, hatten sie, ihr Mann Marco sowie Vereinsmitglied Christine Funk die Idee mit der Igelklappe, die seit November vor ihrem Haus in der St. Nikolauserstraße 26 in Großrosseln-Naßweiler steht. Als Vorbild diente ihnen die Babyklappe von Krankenhäusern. "Wir haben einen Kaninchenstall so umgebaut, dass er einen isolierten Schlafbereich hat sowie einen Bereich mit Futter und Wasser", beschreibt Maas die "Klappe". Für die kalte Zeit liegt ein Heizkissen bereit, das sich nach dem Entpacken selbstständig auflädt, denn Igel mögen es warm. Hierein kann der Finder den hilfsbedürftigen Igel legen und dann den Kasten verschließen, denn in die Klappe darf nur ein Tier: "Sonst gäbe es Mord und Totschlag. (SBZ12/NOV.01390 Saarbrücker Zeitung, 05.11.2012; Babyklappe für kranke Igel)
Als Kosten für den Tiefbau, die Verlegung des Rohrs sowie zwei Schächte gibt Enrico Bachmann rund 27 000 Euro an. Hierein fällt nicht der Deckenschluss der Straße, da er als Instandsetzung abzurechnen sei, erklärt der Leiter der Tiefbauverwaltung weiter. Der Rat beschloss die Baumaßnahme einstimmig. (so) (SZE16/DEZ.03417 Sächsische Zeitung, 08.12.2016, S. 15; Regenentwässerung beschlossen)
Um 17.15 Uhr schließt sich die Busabfahrt zur 22. FEN-Auftaktsitzung (Föderation Europäischer Narren) in Knetzgau an. Hierfür wurden gleich drei Programmpunkte aus Untererthal nominiert: der Gardetanz der Prinzengarde, der Showtanz der Großen Garde und die Bütt von Ruth Neder und Bettina Hügel. Am 14 Januar fährt das Untererthaler Prinzenpaar, Inge I. und Georg I. mit einer Abordnung zum 2. Prinzenpaar-Treffen nach Albertshofen, und tags darauf wird der Jubiläumsabend "50 Jahre KOKAGE Wiesentheid" aufgesucht. (SAZ11/JAN.00616 Saale-Zeitung, 08.01.2011, S. 10; ohne Titel)

Kartenwünsche für die Bunten Abende des FC Rottershausen, die am 12., 18. und 19. Februar stattfinden, können Interessierte noch bis Samstag, 22. Januar, in die Boxen in der Metzgerei Bieber, der Bäckerei Stahl sowie auch im Sportheim einwerfen. Der Kartenvorverkauf für
die Faschingsveranstaltungen findet schließlich am Sonntag, 30. Januar statt. Beginn hierfür ist um 16 Uhr im Sportheim des FC. Khw (SAZ11/JAN.01852 Saale-Zeitung, 19.01.2011, S. 7; Kartenwünsche in Boxen werfen)
Ein großes Problem sei der Mainausbau, gegen den sich Fischer seit Jahren wehren. Jüngst zogen Kitzinger Fischer vor das Bundesverwaltungsgericht, da sie mit den Ausgleichsmaßnahmen unzufrieden waren: "Doch ihre Klage wurde abgewiesen." Aktuell überlegen sie laut Silkenat, ob sie auf europäischer Ebene weiterkämpfen sollen. Ginge es nach den rund 500 Flussfischern in Unterfranken, sollten Freizeitsportler per Gesetz davon abgehalten werden, den Main und seine Nebenflüsse allzu intensiv zu nutzen: "Denn der Freizeitdruck hat enorm zugenommen." Immer mehr Menschen finden laut dem bezirklichen Fischereireferenten gefallen am Bootfahren sowie an Wasser- und Jetski. Für Fische bedeute dies Stress pur. Aktuell werde an einem Seitenarm des Mains sogar ein Motorboot-Parcours
geplant. Hiergegen klagten Würzburger Fischer.
Damit sich alle Fans dieses Sportes auf die kommende Saison an den Stränden vorbereiten können, findet am 24. Mai 2008 von 9.00 Uhr bis 18.00 Uhr der 1. Grabower-Beachday statt. Hierhinter verbirgt sich ein Beachvolleyball-Turnier, auf insgesamt 4 Feldern, mit spannen-den Spielen den ganzen Tag. Anmelden können sich begeisterte Amateur Beachvolleyballteams als Mixed oder "Normal"-Team bis zum 13.05. 2008 unter folgenden Telefonnummern:GWaldbad, 03 87 56 / 27 7 12 oder (SVZ08/APR.01056 Schweriner Volkszeitung, 02.04.2008, S. 13; Beachvolleyball für Amateurteams)
Die Hammelburger Wehr führte den Lehrgang auch durch, weil das neue Löschfahrzeug LF 20/20 mit einem Notfallrucksack ausgerüstet ist. Hierin findet sich ein Großteil der medizinischen Geräte, mit denen auch ein Rettungswagen ausgestattet ist. "Wenn wir solche Geräte haben, brauchen wir natürlich auch Leute, die damit umgehen können", betonte Rettungsassistent Maximilian Zoll, der den Kurs gemeinsam mit Frank Karrlein leitete. (SAZ11/FEB.00026 Saale-Zeitung, 01.02.2011, S. 9; Wie Feuerwehrleute Leben retten können)

Grob gesagt geht es bei einem "Spread Ladder Swap" um eine Wette auf die künftige Zinsentwicklung. Das Problem: Die Bank wettet gegen ihren Kunden. "Der Gewinn der einen Seite ist der Verlust der anderen", sagte der Vorsitzende Richter Ulrich Wiechers bei der
Urteilsbegründung am Dienstag. Hierin liege ein "schwerwiegender Interessenkonflikt". Darüber müsse die Bank den Kunden aufklären. (SAZ11/MAR.02932 Saale-Zeitung, 23.03.2011, S. 22; ohne Titel)
Hammelburg Das erste von drei Windrädern nördlich von Gauaschach steht, und nächste Woche soll es Strom liefern. Auch die beiden anderen Windräder sollen bereits eine Woche darauf errichtet sein und ans Netz gehen. Die Gesamtanlage wird eine Leistung von sechs
Megawatt haben und im Jahr voraussichtlich knapp zwölf Millionen Kilowattstunden (kWh) Strom erzeugen. Hiermit können nach Angaben des Betreibers, der Hamburger Firma Wotan, rund 3300 Haushalte mit elektrischer Energie versorgt werden. 9 (SAZ11/JAN.00416 SaaleZeitung, 06.01.2011, S. 1; Strom für rund 3300 Haushalte)
Die CSU-Fraktion hat einen Dringlichkeitsantrag für die nächste Stadtratssitzung gestellt. Hiernach soll die Stadt ein Grundstück für den eventuellen Neubau einer Fachober- und Berufsoberschule (FOS/BOS) in Hammelburg bereitstellen. (SAZ12/MAR.02173 Saale-Zeitung, 19.03.2012, S. 10; CSU für Fachober- und Berufsschule am Sportzentrum) 

Da der junge Fahrer seinen Führerschein zur Zeit wegen eines Fahrverbots bei der Polizei liegen hat, setzte er seine Fahrt aus Furcht vor den Konsequenzen fort, ohne sich um den Schaden zu kümmern. Dabei geriet er jedoch so in Panik, dass er bereits an der
nächsten Einmündung erneut von der Straße abkam und ein Straßenschild umfuhr. Auch hiernach fuhr er einfach weiter. Pech für ihn, dass Anwohner durch die Unfallgeräusche wach wurden und den Vorfall bemerkten. (SAZ12/APR.00009 Saale-Zeitung, 02.04.2012, S. 3; ohne Titel)
Hierneben kann im Rahmen des öffentlichen Straßenverkehrs auch recht schnell der Straftatbestand der Nötigung verwirklicht werden. Dies kann unter Umständen bereits dann anzunehmen sein, wenn ein Fahrzeug auf der Autobahn auf ein anderes Fahrzeug zu dicht auffährt und dies über längere Zeit anhält. (SVZ07/FEB.10453 Schweriner Volkszeitung, 24.02.2007, S. 26; Vollbremsung mit juristischen Folgen)

Aus dem Großbetrieb ist noch zu erfahren, dass hierneben deutschen Ausgaben auch englische gedruckt wurden, so für den britischen Verlag Random House, der wie GGP Media zum Bertelsmann-Konzern gehört. Stephen Esson, Direktor bei Random House in Großbritannien, erhielt aber nicht nur sauber gedruckte Exemplare des Dan-Brown-Bestsellers aus Pößneck, sondern als Dankeschön für die gute Zusammenarbeit auch ein Kunstwerk, das wiederum unmittelbar auf den The Da Vinci Code-Auftrag zurückgeht. (OTZ06/MAI.10520 Ostthüringer Zeitung, 27.05.2006, S. OAPO127; Verwobene Zeichen rufen nach der Entschlüsselung - Sakrileg-Druckplatten)
Noch geht es in Oberbach beschaulich zu. Doch schon am Dienstag nach Ostern wird der Ausbau der Ortsdurchfahrt beginnen. Hierüber informierte Bürgermeister Alfred Schrenk (SPD) im Rahmen der jüngsten Gemeinderatssitzung die Kommunalpolitiker.
(SAZ11/APR.02731 Saale-Zeitung, 21.04.2011, S. 19; Die Ruhe vor dem Sturm)

Der slowakische Fahrer, der am Parkplatz Klöffelsberg wartete, konnte keinen gültigen Versicherungsnachweis vorlegen. Daher untersagte die Polizei ihm die Weiterfahrt bis zur Vorlage einer entsprechenden Bescheinigung. Hierum wollte sich die Firma kümmern.
(SAZ12/SEP.00875 Saale-Zeitung, 08.09.2012, S. 9; Lkw mit defektem Reifen und ohne Versicherung unterwegs)
Markus Reeh Hammelburg Immer mehr Menschen rutschen in Deutschland unter die Armutsgrenze, und davon bleibt natürlich auch der Altlandkreis Hammelburg nicht verschont. Die Zahl derer, die auf Hilfe vom Staat und soziale Einrichtungen wie Kleiderkammer und Tafel angewiesen sind, steigt kontinuierlich. Und hierunter sind zunehmend auch ältere Menschen, deren Renten nicht ausreichen, um über die Runden zu kommen. (SAZ11/JAN.00611 Saale-Zeitung, 08.01.2011, S. 9; Zunahme der Armut hat viele Gründe)
Riskanter Alkoholkonsum Suchterkrankungen sind ein enormes gesellschaftliches und auch sozioökonomisches Problem. Die Zahl der an einer Suchterkrankung leidenden Menschen nimmt stetig zu. Aktuell gehen Experten davon aus, dass es in Deutschland etwa 9,3 Millionen Menschen mit riskantem Alkoholkonsum gibt, hierunter 2,7 Millionen mit einem schädlichen Alkoholgebrauch und 1,7 Millionen Alkoholabhängige. Etwa 1,5 Millionen Menschen leiden an einer Medikamentenabhängigkeit (größte Teilgruppe: Frauen in der zweiten Lebenshälfte), 150 000 sind abhängig von so genannten harten Drogen. (SAZ11/JAN.01234 Saale-Zeitung, 14.01.2011, S. 38; Ein Medikament gegen Alkoholsucht)

Viele Polit-Promis getroffen War sie zu Beginn bei öffentlichen Auftritten noch etwas unsicher, so kann sie mittlerweile ohne Probleme eine Rede vor vielen hundert Menschen halten. Stolze 160 Termine hat sie seit 2008 absolviert, hierunter auch einige im Ausland, und dabei etliche hochrangige Persönlichkeiten kennen gelernt. So traf sie in Bad Kissingen mit Bundeskanzlerin Angela Merkel zusammen, in Hammelburg sprach sie mit Bundespräsident Christian Wulff, und den bayerischen Ministerpräsidenten Horst Seehofer hat sie gleich
mehrfach getroffen, zuletzt in München. (SAZ11/JUN.01543 Saale-Zeitung, 15.06.2011, S. 9; "Ich würde es immer wieder machen")
Der Sachausschuss Caritas war sehr zufrieden mit der Haussammlung, bei der wieder mehr als 700 Euro gespendet wurden. Hiervon bleiben 30 Prozent in der Pfarrei. Davon werden etwa die Weihnachtspäckchen für die Senioren finanziert. Pfarrer Lux gab einen Überblick über Vergangenes und Geplantes in der Pfarreiengemeinschaft. So erwähnte er, dass er die Arbeiten nicht alle alleine bewerkstelligen könne und auf die Hilfe seiner Hauptamtlichen, aber insbesondere auch auf die der Ehrenamtlichen angewiesen sei. (SAZ11/APR.02013 SaaleZeitung, 16.04.2011, S. 6; Die Arbeit wird auf viele Schultern verteilt)
Aura Die jährliche Mitglieder-versammlung des Feuerwehrvereins der Wehr Aura findet am kommenden Donnerstag, 6. Januar, in der Festhalle statt. Beginn ist um 19.30 Uhr. Hierzu ist die gesamte Ortsbevölkerung, insbesondere die aktiven Dienstleistenden der Wehr sowie
sämtliche Mitglieder des Feuerwehrvereins, willkommen. Auf der Tagesordnung stehen unter anderem Berichte der Gruppenführer und des Kommandanten. Im Anschluss werden die Neuwahlen der Vorstandschaft durchgeführt. Danach sollen die neuen Mitglieder aufgenommen werden. (SAZ11/JAN.00084 Saale-Zeitung, 03.01.2011, S. 10; Neuwahlen beim Feuerwehrverein)
Jetzt haben die Wissenschaftler das Testverfahren weiterentwickelt, bei dem ein Teelöffel Blut ausreicht, um im Organismus zirkulierende Tumorzellen schon in sehr frühen Stadien nachzuweisen. Hierzu haben die Wissenschaftler einen winzigen Silikonchip entwickelt, der mit mehreren Zehntausend Antikörpern beschichtet ist. Wird dieser Mikrochip mit Blut benetzt, trennen sich die bösartigen Zellen von normalen Zellen und haften an den Antikörpern. Die anhaftenden Krebszellen können mit gewissen Färbemethoden nachgewiesen und zum "Leuchten" gebracht werden. Nach Aussagen der Wissenschaftler ist das Verfahren in der Lage, die minimale Menge von zehn Krebszellen pro Milliliter
Blut aufzuspüren. Die neue Methode ähnelt dem ebenfalls gängigen Verfahren der Biopsie, also der Entnahme von verdächtigem Gewebe. Allerdings ist hierzu kein chirurgischer Eingriff nötig, wenige Blutstropfen genügen. (SAZ11/JAN.00411 Saale-Zeitung, 05.01.2011, S. 34;  Ein Teelöffel Blut für die Diagnose)

Damit nun das Inventar - Tische, Stühle, Schränke - angeschafft werden kann, musste zunächst die Genehmigung der Mitgliederversammlung eingeholt werden. Sie erteilte den Auftrag und gewährte ebenso einstimmig die Entlastung des Vorstands, die Kassenprüfer Albin Keßler und Joachim Voll erbeten hatten. Grundlage hierzu bildete der ausführliche Kassenbericht von Kassierer Christian Rost, der eine einwandfreie Bilanz vorlegen konnte. (SAZ11/JAN.00735 Saale-Zeitung, 10.01.2011, S. 5; Klein, aber unverzichtbar)
anderes Auto Oberthulba Nachträglich gemeldet wurde der Polizei ein Unfall, der sich am Donnerstag in Oberthulba ereignet hat. Wie der Fahrer eines Suzuki Vitara angab, befuhr er am Donnerstag zur Mittagszeit die Schlimpfhofer Straße und wollte an der Kissinger Straße nach rechts abbiegen. Eine 18-jährige Peugeot-Fahrerin, die auf der Kissinger Straße unterwegs war, wollte ihr Fahrzeug wenden und fuhr hierzu rückwärts in die Schlimpfhofer Straße ein. Dabei übersah die 18-jährige den herannahenden Suzuki, und es kam zum Zusammenstoß. Es entstand Sachschaden an den Fahrzeugen in Höhe von circa 1000 Euro. (SAZ11/JAN.00746 Saale-Zeitung, 10.01.2011, S. 7; ohne Titel)
Vorsitzender Leo Meder berichtete von über 30 Veranstaltungen. Hierzu gehörten Kameradschaftsabende, Wanderungen, kirchliche und gesellige Veranstaltungen, wobei sich die Wehr um die Verkehrsregelung kümmerte oder mit Abordnungen beteiligte, Aktionen zum Ferienprogramm und Festbesuche bei benachbarten Vereinen. Für den Kameradschaftsabend am 22. Januar um 19 Uhr bat Leo Meder um Anmeldungen. (SAZ11/JAN.00748 Saale-Zeitung, 10.01.2011, S. 8; Viel Lob für engagierte Floriansjünger)

Danach landete Lepper als freier Mitarbeiter in Ammanns Museum für Moderne Kunst und der nicht minder bekannten Kunsthalle Schirn. Bis zu sieben Führungen leitete Lepper täglich, fühlte sich aber etwas zerrissen zwischen Vermittlungsfreude und "Kulturindustrie". In jener Zeit gab er auch ein Comeback an der Gießener Uni - als Dozent an den Instituten für Didaktik der politischen Bildung und Kunstgeschichte. Hierzwischen gebe es viel mehr Verbindung, als mancher denken würde, begründet Lepper die auf den ersten Blick ungewöhnliche Kombination. (GIZ17/FEB.00813 Gießener Anzeiger, 07.02.2017, S. 12; Ein anpackender Sozialromantiker...) 
Angeblich mault der Franke gern, er macht gerne nieder. Am liebsten sich selbst und das, was er hat. Der Kissinger mault über die Kur. "Die Kur ist tot", lautet ein oft gehörter Satz, wobei offenbleibt, was da mit Kur gemeint ist. Die private Vorsorge, die
Stationäre Rehabilitation oder die Anschlussheilbehandlung? Schaut man auf die Statistik, hat die Übernachtungszahl bei den Versicherungsgästen sogar leicht zugenommen. Es kommt darauf an, was der Standort Bad Kissingen aus seiner Kompetenz macht. Zum Beispiel die
Klinik am Kurpark mit ihrer Kira-Studie. Die "Kur" ist nicht tot. (SAZ11/JAN.00062 Saale-Zeitung, 03.01.2011, S. 1; Die Kur ist)

Nach drei Siegen und einem Remis gegen den TSV Nordheim standen die Waldberger schon vor ihrem letzten Gruppenspiel als Halbfinalteilnehmer fest, doch die DJK peilte den Gruppensieg an, um in der Runde der letzten Vier dem SV Rödelmaier aus dem Weg zu
gehen. Den nötigen Punkt hierfür holte Waldberg gegen den Kreisklassisten VfR Bischofsheim. Der musste — wie auch der TSV Uns leben — Lehrgeld zahlen. Unsleben holte den einzigen Sieg gegen den TSV Nordheim — und vermasselte dem damit den Einzug ins Halbfinale, wobei Benjamin Schirber mit der Schlusssirene einen Freistoß zum 2:1 ins Netz hämmerte. Nordheim hätte im letzten Spiel gegen Hohenroth einen Dreier benötigt, lag auch aussichtsreich 2:0 vorne, doch der FSV konterte, schaffte zehn Sekunden vor Ende durch Ralf Schwenkert das 2:2 — damit waren die Hohenröther aufgrund der besseren Tordifferenz — weiter und Nordheim draußen. Der FC Ober-/Mittelstreu wachte zu spät auf: Nach zwei Niederlagen holte die Truppe von Andreas Umla zwar noch sieben Punkte, doch mehr als der vierte Gruppenplatz war nicht drin. (SAZ11/JAN.00165 Saale-Zeitung, 04.01.2011, S. 19; Der Wahnsinn vom Punkt)

In Gruppe B ließ der Bezirksoberligist SV Rödelmaier keinen Zweifel daran, dass der Weg zum Gruppensieg nur über ihn führen würde: Fünf Siege in fünf Spielen sprechen eine deutliche Sprache. Dahinter wurden dem FC Schönau-Wegfurt die größten Chancen eingeräumt — und auch der Kreisligist wurde den Erwartungen gerecht. Er stand schon vor dem letzten Gruppenspiel — dank des Erfolgs im direkten Vergleich gegen den FC Hendungen — als Halbfinalteilnehmer fest. Die A-Klassisten SG Unterweißenbrunn/Frankenheim, TSV Stockheim und TSV Ober-Unterwaldbehrungen machten die Platzierungen in der zweiten Tabellenhälfte unter sich aus. Mit 18 Gegentreffern stellte der TSV Ober-Unterwaldbehrungen die anfälligste Hintermannschaft, wobei Aushilfstorwart Steffen Malzer (BOL-Schiedsrichter) die geringste Schuld traf. (SAZ11/JAN.00165 Saale-Zeitung, 04.01.2011, S. 19; Der Wahnsinn vom Punkt)

Dazwischen sang er ausgewählte, bekannte und weniger bekannte Lieder aus Dowlands "Books of Songs or Ayres" wie "Come away, sweet love", "Sorrow stay", "I saw my lady weep", "What poor astronomers!" oder, natürlich, "Fine knacks for ladies", aber auch einige Lieder von Claudio Saracini, Giulio Caccini, Claudio Monteverdi oder Pierre Guédron. Dazu gab's ein paar kleinere Instrumentalstücke, wobei John Bulls "In Nomine" für Cembalo solo — im Elfvierteltakt geschrieben, aber ein bisschen etüdenhaft einfallslos — aus der emotional
geprägten, mal heiteren, mal melancholischen Linie des Abends deutlich herausfiel. (SAZ11/JAN.00597 Saale-Zeitung, 08.01.2011, S. 6; Eine musikalische Expedition, die nie zum Ziel führte)
Wobei er die Anforderungen, die allein schon die Textmenge an die einzige Sängerin stellt — und auch an das Publikum — dadurch bewältigbar macht, dass der Gesangspart zwar durchaus emotional exaltiert geführt ist, dass er aber auf unsinnige Intervallquälereien um
ihrer selbst willen verzichtet. Die Solistin hat immer die Möglichkeit, Freiräume für die Gestaltung zu nutzen, nicht von der Technik in den Würgegriff genommen zu werden, erzählend zu singen. (SAZ11/JAN.00598 Saale-Zeitung, 08.01.2011, S. 6; Vom großen Dämon der Rastlosigkeit)
Vorsitzender Leo Meder berichtete von über 30 Veranstaltungen. Hierzu gehörten Kameradschaftsabende, Wanderungen, kirchliche und gesellige Veranstaltungen, wobei sich die Wehr um die Verkehrsregelung kümmerte oder mit Abordnungen beteiligte, Aktionen zum Ferienprogramm und Festbesuche bei benachbarten Vereinen. Für den Kameradschaftsabend am 22. Januar um 19 Uhr bat Leo Meder um Anmeldungen. (SAZ11/JAN.00748 Saale-Zeitung, 10.01.2011, S. 8; Viel Lob für engagierte Floriansjünger)

Bevor Landrat Thomas Bold auf das Thema "Generationenfreundlicher Landkreis" einging, streifte er zunächst die Kreistagspolitik. Dabei betonte Bold, dass 2010 auch im Landkreis ein wirtschaftlicher Aufschwung erkennbar sei, wobei aufgrund der besonderen Stellenwerte im
Fremdenverkehr, der Kur und des Baugewerbes, die Beschäftigungszahlen schwanken. Dass die Krise aus 2009 überwunden sei, zeige auch, dass bei den Schulabgängern eine hervorragende Ausbildungsquote zu verzeichnen sei, die schon jahrelange nicht mehr so gut war. (SAZ11/JAN.00756 Saale-Zeitung, 10.01.2011, S. 12; Gemeinde würdigt die über 70-Jährigen)

"Versteigerungen drohen" Doch davon sei der Arbeitsmarkt meilenweit entfernt. Es gebe immer mehr Menschen, die nicht angemessen bezahlt würden, zum Beispiel Verkäuferinnen oder Friseurinnen, und trotz Arbeit nicht genug Geld zum Leben hätten. Sie zahlten hierdurch auch nur geringe Beträge in die Rentenversicherung ein, wodurch ihnen auch im Alter Armut drohe. (SAZ11/JAN.00611 Saale-Zeitung, 08.01.2011, S. 9; Zunahme der Armut hat viele Gründe)

Drei Verfahren möglich Schulte stellte drei mögliche Verfahren vor. Das erste ist die Selbstveranlagung der Bürger. Hierbei geben die Grundstücksbesitzer anhand eines Fragebogens die erforderlichen Angaben an die Abrechnungsstelle. Nachteil dieses Verfahrens sei die Überforderung mancher Betroffener und die Möglichkeit zu Falschangaben, wodurch ein erhöhter Beratungs- und Kontrollaufwand entstehe.
(SAZ11/JAN.03359 Saale-Zeitung, 31.01.2011, S. 9; Abwassergebühren bleiben Thema in Ramsthal)
Der Vermieter tauschte daraufhin die Schließanlage in dem Wohnhaus aus. Von dem Mieter
verlangte er Schadensersatz. Ohne Erfolg: Ein Mieter sei zwar verpflichtet, alles zu unterlassen, wodurch an dem Mietobjekt Schaden entstehen könne, befanden die Richter. Hierzu zähle auch die sichere Aufbewahrung der Haus- und Wohnungsschlüssel. Der Mieter habe aber mit der Nutzung des Wertfachs seiner Verpflichtung Rechnung getragen. dpa (SAZ11/FEB.00750 Saale-Zeitung, 05.02.2011, S. 50; Schlüssel sind im Wertfach sicher genug)
Bislang verwendete Knauf Gips aus Rauchgas-Entschwefelungsanlagen: Der fällt bei Kraftwerken an, wenn die Abgase entschwefelt werden. Wofür die Natur Million Jahre braucht, geschieht dann in wenigen Stunden. Doch immer mehr Kohlekraftwerke gehen vom Netz und weniger Abgase bedeuten weniger Gips. Knauf setzt Naturgips zu und weil die Iphöfer langfristig planen sucht der Bohrtrupp neue Vorkommen. (SAZ11/JAN.00310 Saale-Zeitung, 05.01.2011, S. 8; Auf)

Während andernorts die Veranstalter mit dem Blitzeis und den damit verbundenen spiegelglatten Straßen haderten und Turniere absagen mussten, hatten sich im Römershager Schul- und Sportzentrum tatsächlich alle 16 Mannschaften eingefunden — und das trotz des frühen Turnierbeginns um 9.30 Uhr. "Ein Kompliment an die Mannschaften, die die Anreise gewagt haben. Das spricht auch für unser Turnier, wenn die Leute trotz solcher Bedingungen zu uns kommen", so Turnier-Organisator Jürgen Breitenbach vom ausrichtenden SV Römers hag über die treue Kundschaft. Nicht nur das Glatteis hatte den Veranstaltern im Vorfeld Kopfzerbrechen bereitet. "Die Turnhalle war ja aufgrund der Schneemassen zuvor gesperrt gewesen. Aber die Stadt hat das Hallendach dann räumen lassen, wofür wir uns an dieser Stelle sehr herzlich bedanken möchten", freute sich Breitenbach über den Sportsgeist der Entscheidungsträger. (SAZ11/JAN.00642 Saale-Zeitung, 08.01.2011, S. 20; Ein spezieller Treue-Beweis)

IP-Adresse - wofür steht das eigentlich? IP (gesprochen: Ei Pi) steht für "Internet Protocol". Auf Deutsch: Internet-Protokoll. Das alte System aus Ziffern und Punkten wurde IPv4 abgekürzt. Das bedeutet Internet-Protokoll, Version 4. Eine Adresse kann so aussehen: 217.79.215.248. (SAZ11/FEB.00722 Saale-Zeitung, 05.02.2011, S. 34; ohne Titel)
La Niña (spanisch für "das Mädchen") ist ein Wetterereignis, das häufig im Anschluss an El-Niño auftritt. Es ist eine außergewöhnlich kalte Strömung im äquatorialen Pazifik, sozusagen ein Anti-El-Niño. Durch die kalte Strömung entwickelt sich über Indonesien bei starken
Passatwinden ein starkes Tiefdruckgebiet. Dadurch kühlt sich der östliche Pazifik weiter ab und es gibt in Indonesien viel Regen, wogegen in Peru kaum Regen fällt. Quelle: Wikipedia (SAZ11/JAN.01837 Saale-Zeitung, 19.01.2011, S. 34; Wettermacher)

Immer wieder greift er mit skurriler Logik auf seine Protagonisten zurück: Mal stirbt Dörtes Katze eines nicht natürlichen Todes, wobei er die Ursache mit einen dezenten "Bobom — bobom" des Autos andeutete, mal lässt er Dörte und "dat Uschi" sich sieben Kilometer von der geplanten Windpark-Standorts an Bäume anketten, um den selten "Nußbaum-Zutzler" zu schützen, wobei die Hilferufe vom Landwirt auf dem Gülle verwirbelnden Bulldog nicht gehört werden. Dazwischen ein wenig Politik, wobei er mit dem "Hand-Dreieck" die Kanzlerin nur andeuten musste, wogegen "Plagiator" Guttenberg wenigstens einmal durch den Kakao gezogen wurde, und Lafontaine als "geiler Oscar mit dem heißesten Schnittchen des Kommunismus" für Heiterkeit sorgte. (SAZ12/MAR.00422 Saale-Zeitung, 05.03.2012, S. 6; "Dreggsagg")
Die Spannung steigerte sich, als die bisherige Rekordhöhe von 1,70 Meter von verbleibenden sechs Reiterinnen des Vereins übersprungen werden konnte. Da die vorhandene Mauer bislang lediglich bis 1,70 Meter gebaut werden konnte, hatte man entsprechende Vorsorge zum Höherbau getroffen. Bei der Mauerhöhe von 1,80 Metern, wohinter Parcourchef Klaus Conrad und seine Helfer nicht mehr wahrzunehmen waren, wuchs beim sachkundigen Publikum der Respekt vor dem Mut der im Rennen verbleibenden Damen, dieses Bauwerk mit ihren Pferden bewältigen zu wollen. (SBZ03/JAN.02430 Saarbrücker Zeitung, 08.01.2003; Die Jüngste sprang am höchsten)

Müller, Ehrenpräsident der Narrengilde, kam als Sultan von Marrakesch, als der Herrscher im Orient auf die Bretter, die auch für Narren die Welt bedeuten. Er erzählte von Haremsdamen und Eunuchen und auch davon, wie er die zwischenmenschlichen Positionen in seinem
orientalischen Palast umfunktionierte. Rudi Walz erntete tosenden Applaus in seiner Rolle als "Köllertaler Michel." Außer Rand und Band gerieten die Damen bei den Vorführungen des "Oberpolizisten Patrick" der mit einem Strip doch schon ziemlich gewagt zur Sache ging. "Die Glocken von Rom" ließen das Männerballett der Karnevalsgesellschaft "Die Eule" Rußhütte erklingen: eine umwerfende Show. Die Gildesänger hatten ihre Auftritte mit bekannten Melodien und leicht veränderten Texten, die Erotic lieferten. An den Zuckerhut der
Copacabana entführte der Show-Tanz der Sa-Na-Gi-Dancers, wohinter sich die große Garde der Narrengilde verbirgt. Heribert Wagner und Willi Wagner übten sich als erotisches Gesangsduo, während Sarah Lee Bungert als "Es Quickie" letztes Eis schmelzen ließ.
(SBZ03/FEB.06572 Saarbrücker Zeitung, 17.02.2003; Bei der Premiere knisterte es vor Erotik)
Im Rund gestellte Tische und Stühle, ein allzeit bereiter Kühlschrank, an dem sich jeder nach Lust und Durst bedienen darf, eine überdimensionale Tigerente in einer Ecke: nur wenig erinnert daran, dass man es hier mit einer Fahrschule zu tun hat. Wohinter durchaus System steckt:,,Bei unseren Stunden geht es oft lustig zu. Da wird viel gelacht." Sturen Frontalunterricht hätte seine in der Regel junge Klientel lange genug gehabt. (SBZ04/AUG.04411 Saarbrücker Zeitung, 12.08.2004; Kein tröger Unterricht: Sven Kirsch betreibt die etwas andere Fahrschule)
Entsprechend hoch durften die Erwartungen des Publikums sein. Und um es gleich vorweg zu sagen: Der Abend wurde zu einer tänzerischen Sensation. Wobei man ihn, begründet in den Choreographien, durchaus in zwei Teilen erleben konnte. Denn Mauro Bigonzetti hat sich
zwischen 1994, als er erste Verbindungen zu Aterballetto knüpfte, und 2006- aus dem Jahr stammt die jüngste Choreographie des Abends — nicht unbedingt grundlegend gewandelt, aber seine stilistischen Ausdrucksmittel erweitert. Oder um es anders auszudrücken: Je älter seine Arbeiten sind, desto athletischer sind sie. Je jünger, desto leichter, tänzerischer — womit er durchaus im Trend liegt. (SAZ11/JAN.01106 Saale-Zeitung, 13.01.2011, S. 4; Von der betörenden Leichtigkeit der Schwerstarbeit)

In der Frauenklasse verpasste Julia Wenzke vom TSV Münnerstadt nur knapp den Medaillenrang. Sie lief die 400 Meter in 61,95 Sekunden und wurde damit Vierte. Im sehr stark besetzten Rennen über 200 Meter lief die Physiotherapeutin 27,41 Sekunden, womit sie aber letztlich das Finale verpasste. (SAZ11/JAN.02910 Saale-Zeitung, 27.01.2011, S. 21; Dreisprung fest in Kissinger Hand)
Klaus Angerstein Der Schwarzspecht oder auch Dryocopus martius ist der Online-Enzyklopädie Wikipedia zufolge ein in Mitteleuropa weit verbreiteter Brutvogel, der selbst fragmentierte und kleinflächige Wälder besiedelt. Sogar in den Reichswaldfragmenten in Nähe des Nürnberger Flughafens scheint er sich wohl zu fühlen. Und zwar in möglichst hochstämmigen Bäumen. Womit die Probleme beginnen. Die Wipfel solch hochstämmiger Bäume übersteigen oft genug die Grenze dessen, was der Sicherheit auf bundesdeutschen Flughäfen zuträglich ist. 35 Meter hohe Bäume neben der Start- und Landebahn? Schwarzspechte mögen das vielleicht, für einen anderen Vogel — den Airbus beispielsweise — könnte das zu einem Sicherheitsrisiko werden. Weshalb die Vorschriften klar besagen: Die Bäume müssen weg. Damit der Airbus sicher starten und landen kann. Auch der Bund Naturschutz hat natürlich viel für Sicherheit übrig. Insbesondere, wenn es um den Schutz des Schwarzspechts geht. Der sei in seinem Bestand europaweit gefährdet. Die übliche Totschlagargumentation also. (SAZ11/JAN.03074 Saale-Zeitung, 28.01.2011, S. 23; Schwarzspecht contra Airbus)

Ähnliches gilt für die Reserve des FC 06 Bad Kissingen angesichts der Verpflichtungen von Matthias Beck und Benedikt Wedlich für die Bezirksliga-Elf. Womit gewährleistet sein dürfte, dass die 06er auch in der Rückrunde eine gelungene Mischung aus Talenten und Routiniers auf's Grün schicken können. Den Verein verlassen hat Christoph Kohlhepp, der zum FC Westheim wechselt. (SAZ11/FEB.00498 SaaleZeitung, 04.02.2011, S. 12; Führungs-Quartett steht zu ehrgeizigen Zielen)

Auf bessere Zeiten hofft auch Klaus Katzenberger, Vorsitzender des FC Reichenbach . Schließlich haben sich die Reihen der verletzten Spieler endlich gelichtet, womit unter dem neuen Trainer Marc Hartmann das Saisonziel "10. Platz" offensiv angegangen werden darf.
Seinen Beitrag dazu leisten will künftig Keeper Steffen Kleinhenz, der von der DJK Schlimpfhof zu den Teutonen wechselte. (SAZ11/FEB.00498 Saale-Zeitung, 04.02.2011, S. 12; Führungs-Quartett steht zu ehrgeizigen Zielen)
Betrifft: "Bloß nicht zurücktreten" vom 22. Februar:G"Ich rechne schon lange damit, dass seine Gegner so lange in seiner Lebensgeschichte herum wühlen, bis sie was finden, womit sie ihm ans Bein pinkeln können'. Dieser Satz fiel heute früh hier. Er ist nicht von mir, aber er
könnte es sein. (SAZ11/FEB.02925 Saale-Zeitung, 23.02.2011, S. 19; Was zu erwarten war)
Im vergangenen Dezember wurde das Gutachten eines Rechtsmediziners präsentiert, wonach die Frau frühestens um 23.45 Uhr gestorben ist. Dass beide Opfer um 23.30 Uhr getötet wurden, ist nach Angaben des Sachverständigen nicht unmöglich, aber sehr unwahrscheinlich. Wie Landgerichtspräsident Wich-Knoten dazu erklärte, ist der Angeklagte den Erkenntnissen zufolge in Tatortnähe gewesen, allerdings wohl nicht zu der Zeit, als das Liebespaar erschossen wurde. Für die Bluttat gibt es keine Zeugen, auch die Waffe fehlt bisher — eine schwierige Beweislage. "Das ist eine Indiziengeschichte", sagte Wich-Knoten. (SAZ11/JAN.00511 Saale-Zeitung, 06.01.2011, S. 25; Angeklagter auf freiem Fuß)

In keinem anderen Bundesstaat haben die politischen Emotionen im vergangen Jahr derartige Wellen geschlagen wie in Arizona. Höhepunkt war der Versuch der Regierung in Phoenix, superstrenge Maßnahmen gegen Ausländer einzuführen. In letzter Minute konnte ein
Bundesgericht die Absicht kippen, wonach die Polizei praktisch jeden Ausländer jederzeit kontrollieren kann, ob er illegal im Land ist. Zeitweise hatte der Streit das ganze Land aufgewühlt und die überhitzten Gemüter weiter angestachelt. Doch unter politischen Psychologen ist es längst gängige Erkenntnisse, dass ein solches Klima idealer Nährboden für politische Wirrköpfe und Gewalt ist. (SAZ11/JAN.00797 Saale-Zeitung, 10.01.2011, S. 20; ohne Titel)
Die ägyptische Führung unter Präsident Mubarak schweigt weiter zu den Protesten. Das einzige Zugeständnis war am Donnerstag eine Meldung der staatlichen Medien, wonach das Parlament am kommenden Sonntag über Maßnahmen zur Armutsbekämpfung, eine Anhebung des staatlichen Mindestlohnes und eine bessere Gesundheitsversorgung debattieren soll. Seit Beginn der Proteste wurden nach Darstellung ägyptischer Medien mindestens sechs Menschen getötet. (SAZ11/JAN.03071 Saale-Zeitung, 28.01.2011, S. 23; Proteste erreichen den Jemen)

Und haben Sie dann überhaupt noch Zeit, andere Dinge zu tun? Ich lese ja nicht alle Texte bis zum Ende. Bei manchen stelle ich schon nach fünf bis sechs Seiten fest: Das kommt nicht in Frage. Woran merken Sie das? Manchmal passt das Thema einfach nicht zu uns. Oder die Geschichte ist zu brutal. Wir geben in meinem Bereich ja vor allem Geschichten
für Kinder und Jugendliche heraus. Manchmal ist es aber auch langweilig geschrieben. Oder die Idee ist alt. (SAZ11/JAN.02234 SaaleZeitung, 21.01.2011, S. 30; "Leidenschaft für Sprache, Liebe zu Wörtern")
Ein überdurchschnittlich hoher Prozentsatz türkischstämmiger Jugendlicher
beendet die Schule ohne Abschluss — woran das liegt, ist umstritten. Die Auszubildende Özen ist inzwischen im dritten Lehrjahr und möchte mit der neuen Zusatzqualifikation "Wirtschaftskennerin Türkei" ihre Chancen auf dem Arbeitsmarkt verbessern. Dazu wird sie neben ihrer Ausbildung von Februar an zusätzlich noch 130 Unterrichtsstunden etwa in Wirtschaftstürkisch und in Wirtschaftsgeschichte belegen. Bescheinigt wird die Qualifikation von der Industrie- und Handelskammer (IHK) Nürnberg. "Bei mir besteht die Möglichkeit, nach der Ausbildung in die Türkei zu gehen", sagt Özen. Sie sei neugierig auf das Leben in der Heimat ihrer Eltern. Die neue Qualifikation soll ihr dabei helfen, dort einen Job in einem deutschen Unternehmen zu finden. Die Firmen könnten nach Özens Ansicht in vielfacher Weise von ihrer Landeskunde und ihrem Know-how profitieren. (SAZ11/JAN.03291 Saale-Zeitung, 31.01.2011, S. 27; Cigdem Özen will Brücken bauen)

Ungeachtet dessen treten Mandatsträger und Verwaltung mit dem Anspruch an, den Mangel bestmöglich zu gestalten. Dazu hat es ein erstes Treffen gegeben, das hinter verschlossenen Türen stattgefunden hat. Über drei Stunden lang gab es Informationen von Seiten des
Bürgermeisters Ernst Stross (SPD) und von Kämmerer Bernhard Blum. Ohne Details der nichtöffentlichen Beratungen bekannt zu geben, machte das Stadtoberhaupt im Gespräch mit der Redaktion deutlich: "Durch viele Vorgriffe ist der Haushalt 2011 bereits maßgeblich vorbelastet. Jeder weiß, woran wir sind." Bürgermeister Ernst Stross wollte auf Grund der prekären Finanzlage der Kommune damit einfach Verständnis dafür wecken, dass nicht alles Wünschenswerte leistbar sein werde.,Stross verwies auf die laufenden Millionenprojekte Dreifachturnhalle und Hallenbad. Die Einrichtungen müssten auf Grund ihres Alters mit
hohem Aufwand generalsaniert oder gar neu gebaut werden. "Damit sind bereits wesentliche Mittel gebunden", stellte Stross klar. (SAZ11/FEB.02128 Saale-Zeitung, 17.02.2011, S. 9; Mangel bestmöglich gestalten)

Erste Hilfe leisten heißt mit einfachsten Handgriffen, die jeder erlernen kann, Menschenleben retten können. Dazu gehört es, einen klaren Kopf zu behalten und zu wissen, worauf es ankommt. Wichtig ist eine gewisse Selbstsicherheit, und dass Laien, die gerade vor Ort sind, bis zum Eintreffen des Rettungsdienstes überbrücken können. Und dass sie gegebenenfalls die professionellen Retter unterstützen. (SAZ11/JAN.01594 Saale-Zeitung, 17.01.2011, S. 2; Was ist Erste Hilfe?)

Vielmehr können sie sie auch mit dem Hinweis, worauf sie setzen wollen, dem Croupier geben. Das hatte, wie berichtet, während der Ermittlungen der Leitende Oberstaatsanwalt Rainer Vogt, erläutert. Laut Landeskriminalamt aber soll der betagte Stammgast beim Setzen
seiner Chips keine zu spielende Zahl genannt haben. Was es den beteiligten Croupiers leicht machte, ungeachtet des Ergebnisses des Spiels und damit unabhängig von der gefallenen Zahl Gewinne auszubezahlen. (SAZ11/JAN.02576 Saale-Zeitung, 25.01.2011, S. 1; Wenn die
Kugel amerikanisch rollt)
Freizeit Was kann es im Winter Schöneres geben als zu rodeln? Zumindest wenn genug Schnee liegt und ein Rodelhang in der Nähe ist. Worauf gerutscht wird, ist eigentlich egal. (SAZ11/JAN.02647 Saale-Zeitung, 25.01.2011, S. 30; Rodeln ist ein toller Spaß)

Ungewöhnlich viele prominente Spieler für schwindelerregende Summen wechselten die Seiten. Als teuerster Winter-Transfer geht Vorjahres-Torschützenkönig Dzeko in die Historie ein. Den Abgang des Angreifers zum englischen Premier-League-Club ließ sich Wolfsburg
mit 35 Millionen Euro versüßen. Bayern München holte sich den Hoffenheimer Luiz Gustavo für 17 Millionen Euro, worauf sich Kapitän Mark van Bommel wegen der "besseren sportlichen Perspektive" für den AC Mailand entschied. dpa (SAZ11/FEB.00066 Saale Zeitung, 01.02.2011, S. 20; Helmes stürmt künftig für die Wölfe)
Worauf die Narren an den Tischen in der Schwedenberghalle gewartet hatten, das war ein Büttenbeitrag mit einer ordentlichen Portion Lokalkolorit. Sprechende Mülltonnen gaben mit ihrer Schilderung des Dorfgeschehens hierauf die passenden Antworten. Angefangen vom
Fußball-Brachlandproblem, vergessenen Trikots und Reiseerlebnissen der Kicker, weiterhin über willkommene Reihernahrung durch eingesetzte Fischeier in der Saale bis hin zum Diebstahl von Weihnachtsplätzchen und Streugut betrachteten die Mülltonnen ihre Dorfwelt
aus ihrer jeweiligen Sicht. (SAZ11/FEB.02600 Saale-Zeitung, 21.02.2011, S. 11; ohne Titel)
Die Mitglieder applaudierten, allerdings blieb unklar, woraus dieser Gewinn entstanden ist. Vielmehr wurden Nachfragen durch den Hinweis beantwortet, dass alles eingesehen werden kann und es früher auch nicht anders gewesen sei. Für den Haushalt 2011 kalkuliert Beck mit
steigenden Kosten — allein für die Hochwasserschäden sind 4000 Euro eingeplant — und trotzdem mit einem Überschuss. Die Entlastung von Schatzmeister und Vorstand erfolgten einstimmig. (SAZ11/FEB.01649 Saale-Zeitung, 14.02.2011, S. 3; Der Ärger ist noch nicht
verraucht)

Wenn die Schwaden von Pulverdampf draußen verraucht sind und der dicke Nebel im eigenen Kopf im Laufe des Neujahrstags sich allmählich lichtet, nagt gern ein Tierchen an der Seele: der Gewissenswurm. Das alte Jahr hat man sündig beendet und möchte ins neue ganz, ganz anders starten. Nun heißen die wenigsten von uns Saulus, und nach Damaskus will man sich in diesen Zeiten auch nicht so gern auf den Weg machen. Woraus folgt, dass der alte Adam auch 2012 ganz schön alt aussehen und bleiben wird. Hat der gute Vorsatz zum Jahresanfang nicht überhaupt etwas Puritanisches, zutiefst Genuss- und Lustfeindliches, ja Spießiges? Demnächst lebt man von Reformhauskost, geht im härenen Büßergewand und schaut im Fernsehen immer Reinhold Beckmann und Markus Lanz. So raunt das Teufelchen im Kopf bereits merklich lauter, als der G'wissenswurm nagt. Irgendwann in diesem Jahr wird er dennoch siegen. Er hat ja noch 365 Tage Zeit. Bis dahin halten wir's mit dem Philosophen Nietzsche: ". . . mit dem neuen Sündchen löscht man das alte aus"! (SAZ12/JAN.00081 Saale-Zeitung, 02.01.2012, S. 25; Ein Vorsatz:)

So verdeutliche die Nacktheit einiger der Dargestellten beispielsweise, dass der Mensch verletzlich sei. "Letztlich stellt auch dieses Werk existenzielle Fragen, die sich wie ein roter
Faden durch die gesamte Ausstellung ziehen: Wer bin ich? Woraus lebe ich? Worauf hoffe ich?", sagte Lenssen. Wer den von Gierkes Werk gestalteten Raum betrete, werde hinein genommen in die Bühne des Lebens und müsse seinen Platz finden. "Abendmahl ist für mich überall da, wo Feier des Lebens geschieht." (SAZ12/MAR.00145 Saale-Zeitung, 02.03.2012, S. 33; Besucher als Teil des Kunstwerks)
Als ganz persönliche Zutat zum Programm improvisierte Stoiber über gegebene Themen, darunter das Kirchenlied "Was Gott tut, das ist wohlgetan" (worein sich auch das Männlein, das gewöhnlich im Walde steht, mogelte) in Verbindung mit "Wenn der weiße Flieder wieder
blüht". Eine Sternstunde im Orgelzyklus. (SAZ12/SEP.01166 Saale-Zeitung, 12.09.2012, S. 2; Vom Beherrschen großer Räume)

Für ein attraktives Wohnumfeldes sei es oft nur eine Frage, worein man sein Engagement stecke, meinte Wolfgang Becker, Berater der Firma Argus Concept in Sachen Dorferneuerungen, und präsentierte Ideen zu Straßen, Gärten und Plätzen. Ein Tipp: Stauden statt Gras. "Die Zeit, um jede Woche den Rasen zu mähen, kann man in schönere Effekte stecken." (SBZ06/SEP.10248 Saarbrücker Zeitung, 21.09.2006;
hauptzeile 01 Tag mit Dummy-Text Ortskerne zu neuem Leben erwecken)
Die Schobert und Winter GbR aus Strigleben hat zu diesem Zweck auf dem Feld gleich am Straßenrand einen Kasten installiert, worein Sonnenblumenfreunde eine Spende tun können. Ein Euro pro Blume erbitten die Feldbesitzer. Das Geld soll Milchbauern zu Gute kommen.
Denn die haben gegenwärtig zu kämpfen, weil der Preis pro Liter derzeit mit 21,8 Cent so niedrig ist wie schon lange nicht mehr. (SVZ09/AUG.04015 Schweriner Volkszeitung, 08.08.2009, S. 9; Sonnenfeld für die)
Ich denke, es lohnt sich sehr, ein Kind in unserer Schule anzumelden. Unabhängig davon, dass das neue Gebäude und moderne Unterrichtsräume auch äußerlich beste Lernbedingungen bieten, ist das Schulkonzept darauf ausgerichtet, dass alle Kinder eine Chance haben. Die Betonung liegt auf alle, worein wir viel Kraft investieren, ohne dies ständig zu betonen, denn es ist selbstverständlich geworden. Die Mädchen und Jungen werden ebenso auf den Übergang zum Gymnasium nach der sechsten Klasse wie auf das Erreichen eines
Schulabschlusses am Ende der neunten oder zehnten Klasse vorbereitet. (SVZ14/FEB.04593 Schweriner Volkszeitung, 17.02.2014, S. 9; Hauptbeteiligte nicht
einbezogen)
Worein damit? Man könnte eine Obsttüte nehmen, wie sie auch das Werkbundarchiv nutzt. Oder eine Schachtel, die immer was von Schatzkiste hat. (TSP19/JAN.02550 Der Tagesspiegel, 27.01.2019, S. 208; Nummer 11 223 aus der Serie Glänzende Aussichten)
Bundeskanzlerin Angela Merkel (CDU) auf einer Pressekonferenz mit Frankreichs Präsident Nicolas Sarkozy in BrüsselG "Weder Deutschland noch Frankreich haben im Detail dargelegt, worin dieser Wettbewerbspakt besteht." Luxemburgs Ministerpräsident Jean-Claude
Juncker zum von Deutschland und Frankreich vorgeschlagenen Pakt für eine verbesserte Wettbewerbsfähigkeit (SAZ11/FEB.00711 SaaleZeitung, 05.02.2011, S. 31; Gipfelzitate)

Seit den 1990er Jahren wird im Erlebniskindergarten Westheim, einer "Lernwerkstatt für Kinder", nach dem Prinzip der Reggio-Pädagogik gearbeitet. So kam im Jahr 2000 der Dachboden dazu, der das Atelier beherbergt, worin die Kinder malen, handwerklich arbeiten und sich mit naturwissenschaftlichen Themen befassen können. Der Um- und Erweiterungsbau, der nun kurz vor dem Abschluss steht, war notwendig, da der Kindergarten seit zwei Jahren eine Krippengruppe anbietet, die bisher räumlich nicht optimal untergebracht war. Möglich geworden ist er durch die Krippenförderung des Freistaats Bayern, der die Einrichtung von zwölf Krippenplätzen finanziert. (SAZ11/MAR.03900 Saale-Zeitung, 31.03.2011, S. 13; Kindergarten Westheim)

Die Situation entbehrt nicht einer gewissen Ironie. Als die Vorbereitungen für das Nato-Außenministertreffen — das erste in Deutschland seit  1996 — begannen, hatte niemand auch nur die leiseste Ahnung davon, dass sich das Militärbündnis in einem neuen Einsatz in Libyen
befinden könnte. Jetzt überlagert die Operation "Vereinte Schutzmacht" alle anderen Debatten — egal ob Afghanistan-Einsatz oder das künftige Verhältnis zu Russland. Und ausgerechnet Westerwelle, der sein Land beim Kriegseinsatz in Libyen unter keinen Umständen dabei haben will, hat nun zur Aufgabe, die unterschiedlichen Positionen zusammenzuführen. Die Nato hat mit solchen Momenten schon Erfahrung.  Also wird betont, worin man sich einig ist: dass der Diktator Muammar al-Gaddafi endlich abtreten müsse, dass das geschundene Land eine politische Lösung brauche, dass es Sache der Libyer sei, über ihre Zukunft zu entscheiden. (SAZ11/APR.01952 Saale-Zeitung, 15.04.2011, S. 30; Nato-Differenzen)

Schwierige Gespräche stehen seit Mittwoch zwischen zwei wichtigen Politikern an: dem amerikanischen Präsidenten Barack Obama und dem Staatschef von China, Hu Jintao. Hu Jintao war dafür nach Washington, der Hauptstadt der USA, gereist. Zwischen den USA und China gibt es oft Knatsch und Misstrauen. Politikexperten sagen dazu: Die Beziehungen zwischen den Ländern sind angespannt. Und worüber sind sich die beiden nicht einig? Zum Beispiel fordern die USA, dass China politische Gefangene freilässt.  (SAZ11/JAN.02237 SaaleZeitung, 21.01.2011, S. 30; ohne Titel)

Diese Dokumente über die Verhandlungen zwischen Israel und der Palästinenserführung zu publizieren, sei "ein fehlerhaftes Verhalten". Er zweifelte die Echtheit der Dokumente jedoch nicht ausdrücklich an. "Wir verbergen nichts von dem, worüber wir verhandeln", sagte Abbas.
"Wir haben alle Informationen mit den arabischen Staaten geteilt." Der Generalsekretär der Palästinensischen Befreiungsorganisation (PLO) Jassir Abed Rabbo, warf dem Golfemirat Katar, Sitz von Al-Dschasira, gezielte Sabotage vor. Ziel der Berichte sei es, die radikal-islamische Hamas auch im Westjordanland an die Macht zu bringen. (SAZ11/JAN.02674 Saale-Zeitung, 25.01.2011, S. 27; Enthüllungen setzen Präsident Abbas unter Druck)

Wie der Sender Al-Arabija meldete, rief die NDP Mubarak zum Einschreiten auf. Der staatliche Satellitenkanal Nile News zeigte erstmals Bilder von den andauernden Protesten. Dagegen funktionierten Internet und Handys — worüber sich Regierungsgegner und Oppositionelle verständigen — zeitweise nicht mehr. "Heute Morgen hat noch mein ägyptisches Handy funktioniert, das ist aber mittlerweile tot", berichtete die Kairoer Journalistin Ragah Kamel am Freitag. "Das gleiche gilt für mein deutsches Handy. Ich habe weder Internet noch Handy zurzeit." Ein Zeitungsverkäufer rät ihr: "Wenn du in Gefahr gerätst, dann gehe ins nächste Haus, da bist du geschützt." (SAZ11/JAN.03248 SaaleZeitung, 29.01.2011, S. 31; Feuer in Kairo)

"Die Vielseitigkeit macht das Bunte aus", sagen Annette und Elmar Wehner, die schon seit vielen Jahren ins Zahlbacher Schützenhaus kommen. "Die Mischung mit den Showtänzen macht das Ganze auch nicht so eintönig." Michael Frank ist schon seit zwölf Jahren als Akteur mit den Burkardröther Kindsköpf, als Büttenredner und als Regisseur der "Junge Grünner" dabei. Er sagt: "Es ist ein buntes Programm von und für Jung und Alt, mit Männlein und Weiblein." Alexandra Groten vom Organisationsteam der Burkedröther Norr´n ergänzt: "Mich überraschen jedes Jahr aufs Neue die verschiedenen und verborgenen Talente vieler Mitbürger. Außerdem kommt viel Neues zur Sprache, worüber man auch nachdenken muss." (SAZ11/MAR.00089 Saale-Zeitung, 01.03.2011, S. 7; Der letzte Auftritt der "Kindsköpf")

Tatsächlich hat Lammert zwar nur formuliert, worüber sich der Ältestenrat aufgeregt hat. Aber vor einer Woche erst ist er der Kanzlerin mit seinem "Sargnagel"-Vergleich schon einmal in die Parade gefahren. In der CDU wird geraunt, Lammert räche sich, weil die Kanzlerin ihn nicht gefragt habe, als sie vergangenes Jahr einen Bundespräsidenten suchen musste. (SAZ11/MAR.01552 Saale-Zeitung, 12.03.2011, S. 26; Die Ruhige)
Die Kanzlerin verteidigte die Enthaltung Deutschlands bei der Entscheidung des UN-Sicherheitsrats. Sie glaube, dass eine Luftoperation über Libyen "nicht hundertprozentig durchdacht" sei, sagte Merkel am Freitag in einer Libyen-Sondersitzung der Unionsfraktion. Die Bundesregierung erwägt aber, die Nato an anderer Stelle zu entlasten. "Worüber wir mit der Nato im Gespräch sind, das ist die Frage, ob wir im Rahmen der Gesamtbelastung der Nato Aufgaben übernehmen könnten zum Beispiel im Bereich von Awacs in Afghanistan", sagte Merkel. (SAZ11/MAR.02464 Saale-Zeitung, 19.03.2011, S. 25; Nato entschlossen zu Einsatz in Libyen)
Britisches Flair zum Nulltarif... gibt es im Old Bailey, dem historischen Strafgerichtshof, der schon in den Romanen von Charles Dickens mitspielt. Alles sieht dort heute noch genauso aus einschließlich der Richterperücken, die man unter anderem aus "Ein Fisch namens Wanda" mit John Cleese kennt. Einfach reingehen und in irgendeinen beliebigen Prozess reinsetzen. Worum es geht, steht angeschlagen. Nur Fotoapparate und Taschen darf man nicht mitnehmen, und es gibt auch keine Schließfächer. (SAZ11/FEB.02499 Saale-Zeitung,
19.02.2011, S. 47; London muss nicht viele Pfunde kosten)

Mitte des zweiten Spielabschnitts riss der Faden bei der SG. Den Gastgeberinnen gelang es, zum 16:16 auszugleichen. Das Trainerduo Jordan/Wenzke reagierte mit einer Auszeit. "Wir haben unseren Spielerinnen klar gemacht, worum es hier geht und was wir als Mannschaft wollen", so Jordan. Anschließend gelang es den SGlerinnen, wieder Ruhe in die Partie zu bekommen. Routiniert spielten sie nun die letzten Minuten herunter und verließen als verdiente Siegerinnen das Parkett. (SAZ11/FEB.03508 Saale-Zeitung, 28.02.2011, S. 16; Nach der Auszeit wieder auf Kurs) 

Niemand glaubt Ihnen das Versteckspiel und Sie sollten endlich den Mut aufbringen, mit offenen Karten zu spielen. Es weiß ja sowieso
schon jeder, worum es geht. (SAZ11/MAR.01188 Saale-Zeitung, 10.03.2011, S. 2; ohne Titel)

Sie erhalten im Laufe des Tages eine seltsame Nachricht, die Sie nachhaltig irritiert. Worum es sich dabei handelt, wird sich zeigen. Sie dürfen gespannt sein! (SAZ11/APR.00074 Saale-Zeitung, 01.04.2011, S. 2; ohne Titel)

Worum geht es bei diesem Gesetz über Bildungs- und Teilhabeleistungen? Die "Hartz IV"-Sätze für Kinder regeln zwar das tägliche Leben und Überleben, aber sie tragen nicht der Tatsache Rechnung, dass Kinder auch in eine Gesellschaft hinein wachsen müssen, dass sie den Kontakt zu Gleichaltrigen brauchen. Wo das nötige Geld dazu fehlt, springen jetzt die Kommunen mit Fördermitteln ein. (SAZ11/APR.01598 Saale-Zeitung, 13.04.2011, S. 3; Die Kinder können leichter Freunde finden)

Was braucht man nicht alles für eine Erstkommunion: Festkleidung, gutes Essen, Geschenke. Dabei sind das nur Nebensachen. Die achtjährige Katharina erklärt, worum es eigentlich geht. (SAZ11/APR.02771 Saale-Zeitung, 21.04.2011, S. 34; Katharinas aufregender
Sonntag)
Nach einem Empfang durch den neuen Bürgermeister Stephane Perrin im Salle des Fetes (Festsaal) wurden die Münnerstädter Gäste, worunter sich auch elf junge Feuerwehrleute befanden, die guten Kontakt zu den "Pompiers" von Stenay pflegen, in ihre Gastfamilien
verteilt. Dort gab es überall ein mehrgängiges Abendessen, bei dem die Kontakte wieder neu geknüpft wurden. (SAZ11/APR.02710 SaaleZeitung, 21.04.2011, S. 15; Die Gastfreundschaft ist immer riesig)

Bei der Ermittlung der Verkehrsfrequenz wurden an einem Sonntag 1740 Autos gezählt, die durch den Ort fuhren. Der Spitzenwert wurde an einem Mittwoch mit 2708 Fahrzeugen erreicht, worunter 173 Lkw waren. Die meisten Geschwindigkeitsüberschreitungen wurden zwischen 22 und 9 Uhr festgestellt. Am schnellsten waren die Raser aber tagsüber. (SAZ12/JUL.03281 Saale-Zeitung, 30.07.2012, S. 10; Raser im)
All das findet sich in der Musik von "Pipit Farlouse" . Schon 1998 waren die Elsaß-Lothringer zu Gast beim Liedermacherfestival in
Riegelsberg. Ihr leider zu kurzer Auftritt schlug ein wie eine Bombe, was den Kulturverein Riegelsberg nicht ruhen ließ. Jetzt haben sie es
geschafft, das Quartett erneut zu engagieren, und der Andrang in Jochems Kneipe war groß. Kein Wunder: Wenn "Pipit Farlouse" spielen, geht auch an einem total verregneten Samstagabend die Sonne auf. "Pipit Farlouse" sind Vertreter einer sehr modernen Richtung des französischen Chansons. Begonnen haben sie mit elektrisch verstärkten Instrumenten, seit zwei Jahren aber spielen sie rein akustisch: Stimme, Klavier, Gitarre, Bass, Schlagzeug, sonst nichts. Was ihrer Musik sehr zugute gekommen ist, sie ist noch einen Tick durchsichtiger geworden. Worunter Energie und Ausstrahlung aber keineswegs gelitten haben, sie sind vielleicht sogar noch besser geworden als früher. Das fängt an bei der Frontfrau, Catherine Campanella, einer ebenso zierlichen wie kraftvollen Sängerin (und Pianistin), die unter anderem Alain Souchon zu ihren Vorbildern zählt. In den leisen Passagen der Balladen erinnert ihre glockenklare Stimme an Suzanne Vega, genauso kann sie aber jazzmäßig oder regelrecht rockig singen. Campanella schreibt auch die Texte der Band; außer vom zeitlosen Thema Liebe lässt sie sich dabei vor allem von einer längst vergangenen Zeit inspirieren: den Kelten und ihren Sagen. Von König Artus und seinen Rittern handelte etwa ein Lied. (SBZ00/JAN.10873 Saarbrücker Zeitung, 31.01.2000; Groove und Swing mit glockenklarer Stimme)

Alles ist super, nett, hochmotivierte Lehrer gestalten den Unterricht, persönliche Beratungsgespräche finden nach dem Unterricht statt. Könnte es sein, dass einige geschickt ausgewählte Schüler überhaupt keinen Realitätsbezug zu ihrer schulischen Umgebung mehr verspüren? Im Gegensatz zum KBBZ Wadern gibt es in Merzig noch genügend Missstände, die es zu beheben gilt. Wir beanstanden, dass in Merzig eine Klassenstärke von 30 Schülern als normal angesehen werden muss, worunter Schüler, aber auch Lehrer leiden. Auch scheint kein Geld vorhanden zu sein, die ohnehin schon völlig veralteten Schreibmaschinen zu reparieren, damit der Unterricht reibungslos ablaufen kann. Wer sich die Altersstruktur der Lehrer ansieht, wird feststellen müssen, dass vorwiegend ältere Lehrer, schon etwas müde geworden, ihren Unterrichtsstoff monoton im Unterricht umsetzen und damit keineswegs zu den Motivationskanonen zählen, wie es sie in Wadern ausschließlich gibt.
(SBZ00/APR.03164 Saarbrücker Zeitung, 08.04.2000; ohne Titel)

Das GUS-Land liegt an der Grenze Europas zu Asien. Rund 5,3 Millionen Menschen leben dort, darunter Griechen, Türken, Armenier und Russen. In einem Bürgerkrieg haben sich die Abchasen abgespalten und über eine Million Flüchtlinge verteilten sich im ganzen Land.
Alleine 490000 leben derzeit in der Hauptstadt Tbilissi. Vor allem wegen des Bürgerkrieges hat das rund 70000 Quadratkilometer große Land, das entspricht ziemlich genau der Fläche Bayerns, enorme wirtschaftliche Probleme, worunter besonders alte und kranke Menschen
leiden. Im Westen grenzt es an das Schwarze Meer, im Osten an Aserbaidschan und Tschetschenien. Mit seinem mediterranen Klima ist Georgien ein recht fruchtbares Land. Der Verein "Saarländisch-georgische Freundschaft Jugend und Kultur" kümmert sich um junge Leute in Georgien und um einen Austausch zwischen Georgien und dem Saarland. Informationen gibt Wolfgang Wagner unter Tel. (06853) 922992. (SBZ00/APR.08965 Saarbrücker Zeitung, 26.04.2000; Saarländisch-georgische Freundschaft...)
Den Schülern wurde durch die "Tafel" ein Interview mit einer HartzIV-Empfängerin ermöglicht. Die 47-jährige, alleinerziehende Mutter dreier Kinder arbeitet als Sporttrainerin, muss aber auch als Zimmermädchen schuften und Zeitungen austragen, um über die Runden zu kommen. Sie verdient 300 Euro im Monat, wovon berufliche Kosten abgehen. Nachdem sie sechs Jahre versucht hat, alleine für ihre Familie zu sorgen, bezieht sie seit einem Jahr HartzIV. Vorher sei sie zu stolz gewesen, sich als "arm" zu bezeichnen. (SAZ11/JAN.00207 SaaleZeitung, 04.01.2011, S. 5; Die Not wohnt gleich nebenan)
Mit der Vergrößerung des Gebietes wird es auch ein neues Faltblatt geben. "Wir werden versuchen, das etwas größer aufzuziehen, nicht nur für die Gäste, sondern auch für die Einwohner der Region." Mit dem Start der Fahrradsaison im April/Mai werden dann die Elektroräder auch wieder im Haus der Schwarzen Berge auszuleihen sein. Und dass das Fahren mit dem E-Bike so richtig Spaß macht, davon haben sich Geerd Müller und seine Mitstreiter schon selbst überzeugt. Schließlich wollen sie ja auch wissen, wovon sie reden, wenn die Gäste nachfragen. (SAZ11/JAN.02161 Saale-Zeitung, 21.01.2011, S. 15; Stolz auf Deutschlands schönsten Wanderweg 2010)
Wovon diese jungen Menschen träumen und wovor sie sich fürchten, wird vor allem durch Projektionen sichtbar, für die in unterschiedlicher Ästhetik sowohl Bühnenbildner Patrick Bannwart als auch Kostümbildner Falko Herold verantwortlich zeichnen. Mal wirken diese Bilder wunderbar poetisch und märchenhaft, dann wieder sind sie so aufdringlich und aufgebläht, dass sie die Protagonisten zu Statisten degradieren. (SAZ11/JUL.02754 Saale-Zeitung, 23.07.2011, S. 35; Pubertärer Geniestreich mit einigen Fragezeichen)

Wozu die DSV-Läufer dennoch imstande sind, zeigte der Frankenhainer Jens Filbrich. Auf dem klassischen Teilstück diktierte er das Rennen mit. "Ich habe mich richtig gut gefühlt. Doch dann kam ein Sturz dazwischen, und schon waren 20, 25 Plätze verloren. Zudem habe ich mir das Schienbein richtig wehgetan und konnte im Skating nicht so, wie ich wollte", sagte der Thüringer. (SAZ11/JAN.00148 Saale-Zeitung, 04.01.2011, S. 20; Teichmann steigt nach Rang 56 aus)
Eine Bürgerversammlung nur mit Frauen? Das gibt es nur in Fuchsstadt und nur im Fasching. Da wurde der Bürgermeister alias Edgar Stockmann schon auch gefragt, wozu Sonnenkollektoren auf der Nordseite gut seien. Ob jeder dritte Fuschter hässlich ist, sei dahingestellt. Treffe dies auf sie zu, habe sie wenigstens die "Mittlere Reife", sagte Edith Stockmann. (SAZ11/FEB.02594 Saale-Zeitung, 21.02.2011, S. 9; ohne Titel)

Das Fernsehen lieferte die Vorlage für das Publikumsspiel "Die schnelle Minute", bei dem Frank Wenzel Saalkandidaten zur Gaudi des Publikums in verschiedenen Wettkämpfen gegeneinander antreten ließ. Wozu ein Männerballett in der Lage ist, zeigte die "Ramsthaler
Puppenkiste". Seelefant Thorsten Kühnlein, Urmel Frank Herterich, eine Erdmännchenkolonie, die Blechbüchsenarmee oder die Piratenbande — alle Figuren überzeugten. (SAZ11/MAR.00191 Saale-Zeitung, 02.03.2011, S. 11; Von Erdmännchen bis Elfen)

Der CDU-Gesundheitsexperte Jens Spahn zeigte sich enttäuscht von der Stellungnahme des Rats aus Medizinern, Naturwissenschaftlern, Juristen, Philosophen und Theologen. "Es stellt sich einmal mehr die Frage, wozu es einen Ethikrat braucht", sagte der Anhänger eines
kompletten Verbots der "Rheinischen Post". Seine FDP-Kollegin Ulrike Flach verteidigte den Rat. "Es gibt keine vereinheitlichte Ethik", sagte die Anhängerin einer Zulassung. Der Sprecher der Arbeitsgruppe Fortpflanzungsmedizin des Rats, Wolf-Michael Catenhusen, meinte, die Stellungnahme sei hilfreich - Positionen seien überprüft, Aspekte präzisiert worden. (SAZ11/MAR.01133 Saale-Zeitung, 09.03.2011, S. 24; Verstoß gegen das Recht auf Leben?)

Antrag auf Ratenzahlung "Sie sollten künftig besser darauf achten, wozu sie sich verpflichtet haben", sagte Dümig. Der Kläger folgte schließlich dem Rat des Gerichts, seine Klage zurückzunehmen und dadurch wenigstens einen Teil der Prozesskosten zu sparen.
(SAZ11/MAR.02127 Saale-Zeitung, 17.03.2011, S. 16; Ein aussichtsloses Unterfangen)

Überhaupt kann man sich über den Sinn und Unsinn der Fragen streiten. Aber muss man denn bei "Wer wird Millionär?" wirklich alles wissen? "Power of Ten" ist zumindest insofern aufschlussreich, weil man erfährt, wie die Deutschen so ticken. Und weil man denken muss, was sie denken oder zumindest, was sie sagen, was sie denken würden, wozwischen manchmal ein kleiner, aber feiner Unterschied besteht. Soll man zum Beispiel tatsächlich glauben, dass 70 Prozent im Falle von Arbeitslosigkeit für fünf Euro die Stunde Spargel stechen würden? Oder dass nur sieben Prozent Versicherungsbetrug für ausgleichende Gerechtigkeit halten? Solche Fragen sind immerhin noch einigermaßen relevant, auch
die danach, wie viel Prozent der Deutschen sich im Auslandsurlaub schon einmal geschämt haben, Deutscher zu sein. Aber will man unbedingt wissen, wie viele Menschen auf der Toilette telefonieren, "wo das Besetztzeichen eine ganz andere Bedeutung bekommt", wie
Bach kalauert? Da würde man doch gern mal Mäuschen sein, wenn sich die Redaktion wo auch immer die Fragen ausdenkt. (STZ08/APR.05276 Stuttgarter Zeitung, 21.04.2008, S. 16; Telefonieren viele auf dem Klo?)

Ich sage das gerade vor dem Hintergrund des zwanzigsten Mauerfall-Jubiläums. In der DDR erlaubte sich das Politische Übergriffe in allzu viele Lebensbereiche. Die Machthaber hatten nicht nur den Willen, sondern auch den dazu nötigen Staat, Geschicke zu lenken und zu leiten, Lebensentwürfe aufgehen oder scheitern zu lassen. Die Bürger der DDR waren Staatsbürger - unabhängig davon, ob sie ihrem Staat zustimmend oder ablehnend gegenüber standen. Das Politische wehte einem jedem als eisiger Hauch im Nacken. Erschwerend kam hinzu, daß sich die Verhältnisse nicht einfach abwählen ließen; deshalb waren die Wahlen in der DDR nichts, was die Bezeichnung Wahlen verdient hätte. Es gab nichts, wozwischen man wählen konnte; das deutlichste Bekenntnis bestand darin, nicht zur Wahl zu gehen. (TSP09/AUG.03105 Der Tagesspiegel, 24.08.2009; Warum wählen? //
Nicht der Nichtwähler ist eine Gefahr für die Demokratie, sondern die Wahlkämpfe sind es / Von Thomas Brussig)

Die Commode war mit Röcken, Wäsche, Büchern pyramidenförmig aufgehäuft, alle Schubladen herausgezogen, in den Ecken waren Gewehre aller Art aufgepflanzt, die zwei
vorhandenen Stühle waren besetzt mit Büchern, Briefschaften, Hausgerät, wozwischen rote Tücher als Friedensfahnen heraushingen", beschrieb Wilhelm dem Bruder Jacob die spärlich möblierte Dreizimmerwohnung Arnims: "Hier schreibt er mitten in dieser Unordnung die
herrlichsten und göttlichsten Dinge." (TSP12/DEZ.02025 Der Tagesspiegel, 16.12.2012; Es war einmal // ... eine Künstler-WG in der Mauerstraße. Dort lernt der junge Wilhelm viel über Berlin. Weihnachten 1812 veröffentlicht er mit seinem Bruder Jacob Grimm
sein erstes Märchenbuch. Auch dank seiner neuen Berliner Freunde)

"Mit den Donauwellen ist das Leitmotiv vorgegeben: Es geht um flüssige Übergänge, egal wozwischen, wieso und wohin."  (HAA10/DEZ.00902 Hamburger Abendblatt, 07.12.2010, S. 15; Querschläger)


Der Ort symbolisierte für beide ihre Zerrissenheit zwischen Berlin und Hamburg, wozwischen Hallaschka regelmäßig pendelte, um beim NDR das Verbrauchermagazin " Markt" und in Vertretung die " NDR Talk Show" zu moderieren. " Wir wollten unsere Freunde auf halber Wegstrecke treffen." Den Pastor vor Ort konnten sie allerdings nicht davon überzeugen, dass nur der Geistliche aus Anne-Katrins Heimatdorf die kirchliche Trauung übernehmen sollte. " Als wir in die Kirche kamen, standen zwei Pastoren am Altar. Das fand ich erst befremdlich und dann ziemlich gut" , erinnert Hallaschka sich. (HAA18/DEZ.02427 Hamburger Abendblatt, 11.12.2018, S. 6002; " Meine Prominenz ist nur geliehen")'''    
    
"""
#anaphora_classifier_system(all_Das_PAK, language)    